### ISSUE TITLE
登陆显示无效账号

### ISSUE THREAD

**Issue by burenmo** [Notsfsssf/pixez-flutter#104]
网页端可以正常登陆，但是无法红心和关注画师，正版的pixiv app则会无限循环请重新登录，但是重新注册的账号可以正常登陆，请问是我的账号出了什么问题吗？也没发邮件给我

**Comment by Notsfsssf** [comment]
弱密码，需要前往官网修改为强密码

**Comment by burenmo** [comment]
> 弱密码，需要前往官网修改为强密码

用随机密码生成器形成了一个四级强度密码
AgrauAKq2qFf8FzQ
结果同上
新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题

**Comment by Notsfsssf** [comment]
> > 弱密码，需要前往官网修改为强密码
> 
> 用随机密码生成器形成了一个四级强度密码
> AgrauAKq2qFf8FzQ
> 结果同上
> 新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题

有没有试过官方网页登录看站内信，可能是特殊问题

**Comment by burenmo** [comment]
> > > 弱密码，需要前往官网修改为强密码
> > 
> > 
> > 用随机密码生成器形成了一个四级强度密码
> > AgrauAKq2qFf8FzQ
> > 结果同上
> > 新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题
> 
> 有没有试过官方网页登录看站内信，可能是特殊问题

抱歉我不太清楚站内信是什么东西。目前我在通知、私信、还有邮件里没有看到特殊的提醒。我自己已经给pixiv发过邮件反馈过问题，得到的回复是可能客户端安装出了问题让我重新安装，可是这并没有什么效果。

**Comment by Notsfsssf** [comment]
> > > > 弱密码，需要前往官网修改为强密码
> > > 
> > > 
> > > 用随机密码生成器形成了一个四级强度密码
> > > AgrauAKq2qFf8FzQ
> > > 结果同上
> > > 新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题
> > 
> > 
> > 有没有试过官方网页登录看站内信，可能是特殊问题
> 
> 抱歉我不太清楚站内信是什么东西。目前我在通知、私信、还有邮件里没有看到特殊的提醒。我自己已经给pixiv发过邮件反馈过问题，得到的回复是可能客户端安装出了问题让我重新安装，可是这并没有什么效果。

如果方便的话可以把账号密码发送的反馈邮箱，我这边可以看得到日志，当然tg上发也行

**Comment by burenmo** [comment]
账号1250635380@qq.com
密码zch961223
多谢帮忙



---原始郵件---
寄件人： "Perol_Notsfsssf"<notifications@github.com&gt;
傳送時間： 2020年12月13日(週日) 上午9:58
收件人： "Notsfsssf/pixez-flutter"<pixez-flutter@noreply.github.com&gt;;
抄送： "burenmo"<1250635380@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主旨： Re: [Notsfsssf/pixez-flutter] 登陆显示无效账号 (#104)




     
弱密码，需要前往官网修改为强密码
  
用随机密码生成器形成了一个四级强度密码
 AgrauAKq2qFf8FzQ
 结果同上
 新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题
  
有没有试过官方网页登录看站内信，可能是特殊问题
  
抱歉我不太清楚站内信是什么东西。目前我在通知、私信、还有邮件里没有看到特殊的提醒。我自己已经给pixiv发过邮件反馈过问题，得到的回复是可能客户端安装出了问题让我重新安装，可是这并没有什么效果。
  
如果方便的话可以把账号密码发送的反馈邮箱，我这边可以看得到日志，当然tg上发也行

**Comment by Notsfsssf** [comment]
> 账号1250635380@qq.com 密码zch961223 多谢帮忙
> […](#)
> ---原始郵件--- 寄件人： "Perol_Notsfsssf"<notifications@github.com&gt; 傳送時間： 2020年12月13日(週日) 上午9:58 收件人： "Notsfsssf/pixez-flutter"<pixez-flutter@noreply.github.com&gt;; 抄送： "burenmo"<1250635380@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主旨： Re: [Notsfsssf/pixez-flutter] 登陆显示无效账号 (#104) 弱密码，需要前往官网修改为强密码 用随机密码生成器形成了一个四级强度密码 AgrauAKq2qFf8FzQ 结果同上 新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题 有没有试过官方网页登录看站内信，可能是特殊问题 抱歉我不太清楚站内信是什么东西。目前我在通知、私信、还有邮件里没有看到特殊的提醒。我自己已经给pixiv发过邮件反馈过问题，得到的回复是可能客户端安装出了问题让我重新安装，可是这并没有什么效果。 如果方便的话可以把账号密码发送的反馈邮箱，我这边可以看得到日志，当然tg上发也行 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边返回的是`{"has_error":true,"errors":{"system":{"message":"104:無効なユーザーアカウントです。","code":1508}},"error":"invalid_grant"}`无效的用户账户，可能被限制行为了，这个就不知道怎么解决了

**Comment by burenmo** [comment]
好吧，可能只有用新账号了。我也不知道为什么就被限制了。难受。



---原始郵件---
寄件人： "Perol_Notsfsssf"<notifications@github.com&gt;
傳送時間： 2020年12月13日(週日) 上午10:21
收件人： "Notsfsssf/pixez-flutter"<pixez-flutter@noreply.github.com&gt;;
抄送： "burenmo"<1250635380@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主旨： Re: [Notsfsssf/pixez-flutter] 登陆显示无效账号 (#104)




  
账号1250635380@qq.com 密码zch961223 多谢帮忙
 …
 ---原始郵件--- 寄件人： "Perol_Notsfsssf"<notifications@github.com&gt; 傳送時間： 2020年12月13日(週日) 上午9:58 收件人： "Notsfsssf/pixez-flutter"<pixez-flutter@noreply.github.com&gt;; 抄送： "burenmo"<1250635380@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主旨： Re: [Notsfsssf/pixez-flutter] 登陆显示无效账号 (#104) 弱密码，需要前往官网修改为强密码 用随机密码生成器形成了一个四级强度密码 AgrauAKq2qFf8FzQ 结果同上 新账号的密码跟老的一样，但是也能正常登陆，可能不是这方面的问题 有没有试过官方网页登录看站内信，可能是特殊问题 抱歉我不太清楚站内信是什么东西。目前我在通知、私信、还有邮件里没有看到特殊的提醒。我自己已经给pixiv发过邮件反馈过问题，得到的回复是可能客户端安装出了问题让我重新安装，可是这并没有什么效果。 如果方便的话可以把账号密码发送的反馈邮箱，我这边可以看得到日志，当然tg上发也行 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我这边返回的是{"has_error":true,"errors":{"system":{"message":"104:無効なユーザーアカウントです。","code":1508}},"error":"invalid_grant"}无效的用户账户，可能被限制行为了，这个就不知道怎么解决了
