### ISSUE TITLE
进行中的任务在重新启动App之后，状态会变成seed

### ISSUE THREAD

**Issue by FlandiaYingman** [Notsfsssf/pixez-flutter#105]

**Comment by FlandiaYingman** [comment]
seed是一个什么状态？我可以添加一个按钮来重新下载所有seed的任务吗？

**Comment by Notsfsssf** [comment]
Seed是指任务未开始，或者不正常的结束，能够手动重试但未在进行中的任务都是Seed

**Comment by FlandiaYingman** [comment]
> Seed是指任务未开始，或者不正常的结束，能够手动重试但未在进行中的任务都是Seed

能否添加一个重试所有seed的任务的按钮？

**Comment by Notsfsssf** [comment]
> > Seed是指任务未开始，或者不正常的结束，能够手动重试但未在进行中的任务都是Seed
> 
> 能否添加一个重试所有seed的任务的按钮？

可以的
