### ISSUE TITLE
报告个现象:用食指短距离上滑的时候偶尔会判断为左右划？

### ISSUE THREAD

**Issue by yzwik** [Notsfsssf/pixez-flutter#106]
左右翻页的距离判断是不是有点过短？

**Comment by Notsfsssf** [comment]
确实会这样，使用的是原来的material widget没做任何改动，似乎是官方的判断范围不太合适

**Comment by yzwik** [comment]
> 确实会这样，使用的是原来的material widget没做任何改动，似乎是官方的判断范围不太合适

好吧😂
