### ISSUE TITLE
关于r18分流下载的建议

### ISSUE THREAD

**Issue by DLGum** [Notsfsssf/pixez-flutter#116]
1：请求可自定义x_restrict分流等级。
比如设置可自选2，3，4级。

根据x_restrict等级分流的话，对每个人来说可能都不太一样。
比如图片86888359或者86914092，个人认为是十足的涩图。诸如此类还有很多。
目前的分流实在太不完全。

我个人觉得4级分流会比较合适。但别人可能不这么认为。
所以希望可以有自定义等级选定。

另外长按图片看到的x_restrict不是0就是1。
我是不太了解具体参数。我只知道这个参数等级是不止0和1的。

如果能显示精确的x_restrict等级，并且加上自定义分流等级。
那我想对每个人都可以方便设置了。

2：也许可以添加自定义标签分流功能。
比如#魅惑の谷間 之类的标签分流应该一敲一个准。

**Comment by Notsfsssf** [comment]
如果说的是指按x_restrict来筛选，是可以的    
但是这个只能作用于本地，官方的接口大概是不支持增加这个筛选的    
就是说，比方一个接口一次只返回30张illust的数据，我只能做到本地筛出x_restrict为n的那几张，做不到让服务器反给我全是x_restrict为n的30张    
另外这个参数在返回的illust列表里不是0就是1，大概是官方后台对于列表的x_restrict参数没做精细划分，所以就更难实现了

**Comment by DLGum** [comment]
能够实现本地下载时筛选足矣。

**Comment by DLGum** [comment]
> 如果说的是指按x_restrict来筛选，是可以的
> 但是这个只能作用于本地，官方的接口大概是不支持增加这个筛选的
> 就是说，比方一个接口一次只返回30张illust的数据，我只能做到本地筛出x_restrict为n的那几张，做不到让服务器反给我全是x_restrict为n的30张
> 另外这个参数在返回的illust列表里不是0就是1，大概是官方后台对于列表的x_restrict参数没做精细划分，所以就更难实现了

大佬。好像不是根据x_restrict筛选。
是根据sanity_level筛选。
4级左右比较合适。你可以测试一下。
