### ISSUE TITLE
103相关问题

### ISSUE THREAD

**Issue by Tnakh** [Notsfsssf/pixez-flutter#121]
首先感谢作者对此应用的开发，以便我不用翻墙也能正常使用P站。
这是本人第一次在GitHub提出问题，可能会有不周到的地方，还请见谅。
正题如下：
今天使用pixez flutter的时候发生了上一个帖子中说的图片无法加载问题。本着先自行解决的想法，本人先更新了软件，但是还是行不通。考虑到可能是覆盖安装造成的奇妙bug，所以本人选择卸载软件清除数据再重装一遍。于是乎便在登陆时遇到了103问题。相关原因我也在常见FAQ里面确认过了，说是要么密码错误，要么密码过于简单。但是本人之前没有修改过p站密码，哪怕是在ezviewer更替至flutter时期也没有出现过类似问题。所以想问一下开发者，我这种情况是否正常，还是说只有登录官网修改密码这种选择了？

ps：至于前面说的加载问题，我在重装之后用软件生成的账号登录，发现提示加载失败之后就正常显示了。

**Comment by Tnakh** [comment]
更新：今天登录官网提示密码太弱，通过重设密码解决了

**Comment by Tnakh** [comment]
如何在不评论的情况下关闭问题呢

**Comment by Notsfsssf** [comment]
应该是弱密码被p站废弃了，强制要求更新密码，我帮你close吧

**Comment by Tnakh** [comment]
谢谢！有劳老哥了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Notsfsssf/pixez-flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月20日(星期三) 晚上6:51
收件人:&nbsp;"Notsfsssf/pixez-flutter"<pixez-flutter@noreply.github.com&gt;;
抄送:&nbsp;""<510373346@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Notsfsssf/pixez-flutter] 103相关问题 (#121)





 
应该是弱密码被p站废弃了，强制要求更新密码，我帮你close吧
