### ISSUE TITLE
之前我使用的挺正常的，但是之后不知道是因为安装了更新推送，导致我的存储位置有错，所有保存的图片都变成了显示开始下载，显示下载完成，但是没有存储到手机上。

### ISSUE THREAD

**Issue by AndyMerkel** [Notsfsssf/pixez-flutter#128]

**Comment by AndyMerkel** [comment]
saf模式默认开启位置是Download文件夹，但是确认之后提示不能使用download文件夹，而且并没有给出其他文件夹的选择，如果你使用默认，会发现并没有那个文件夹的存在，等于说默认文件夹并没有设置成功

**Comment by AndyMerkel** [comment]
传统模式只能往上一层，或picture文件夹中（不知道咋弄出来的）不能往下一层文件夹，没有子文件夹列表，同时新建文件夹也不能产生效果

**Comment by AndyMerkel** [comment]
于是乎就进入了dead app，只能重新下载了。

**Comment by AndyMerkel** [comment]
存储路径应该要可以复制，方便操作，下载内容也应该要可以在app内部显示，像历史记录界面一样。

**Comment by AndyMerkel** [comment]
我本人也是从18年11月份就开始写flttuer，但是只写了五六个小app，这个软件写的非常棒，很值得学习。

**Comment by AndyMerkel** [comment]
刚才安装了最新的relase，虽然saf仍然不能用，但是设置失败后不会产生令人迷惑的默认路径了。传统模式工作正常。

**Comment by Notsfsssf** [comment]
saf本来就不推荐路径的做法，需要选择非download目录，这个是权限的问题，具体可以参考android开发文档
你需要仔细阅读FAQ
https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md
