### ISSUE TITLE
保存名称

### ISSUE THREAD

**Issue by whycantiusemyname** [Notsfsssf/pixez-flutter#13]
软件的保存名称每次关闭程序后就会清除，导致下一次打开时看任何图都显示已保存，希望能把保存名称永久记忆

**Comment by Notsfsssf** [comment]
我这边测试是生效的，你的保存格式换成了什么，如果是非法的保存名称会被强制替换成默认的，比如把{part}去掉，part是区分同一投稿不同部分的关键字符，或者吧英文{输入为了中文的{

**Comment by whycantiusemyname** [comment]
我安装后默认为空的，然后我使用的是{title}_{user_name}_{user_id}_{part} 为名称，直接用软件内的按钮输入的，设置了后就可以保存图，但后台关掉程序就在启动名称就没了

**Comment by Notsfsssf** [comment]
发个设置名称后的截图吧，我这边测试只要是英文输入的半角符号就不会有问题，而且也能保存
可以点右上角的按钮重置回默认
