### ISSUE TITLE
请问IOS保存图片是保存到了哪里呢？谢谢

### ISSUE THREAD

**Issue by iPixelOldC** [Notsfsssf/pixez-flutter#132]
如题，我这边保存后（两种方法长按和打开大图按保存按钮都试过了），下载也显示成功了，但相册里面没有。然后文件app里面也没找到。所以请问iOS这边是保存到了哪里呢？谢谢🙏
（补充：FAQ也看了，issues里也搜了，但貌似都只有安卓方面的，没有iOS的，所以才开了这个issue来问问ᶘ ᵒᴥᵒᶅ）
（补充2：通过分享按钮，保存到文件夹里面倒是正常的）

**Comment by Notsfsssf** [comment]
默认是保存到/pixez的，我找了iPhone12的朋友和用xcode的simulator测试应该是没有问题的，具体是什么型号呢？
有提示下载完成吗？（第一次会请求权限）

**Comment by iPixelOldC** [comment]
> 默认是保存到/pixez的，我找了iPhone12的朋友和用xcode的simulator测试应该是没有问题的，具体是什么型号呢？
> 
> 有提示下载完成吗？（第一次会请求权限）

我找到问题所在了，相册的权限设置为“选中的照片”，就没办法保存到相册里面。必须为“所有”才行...（至于提示，哪种权限，都有下载完成的提示）

**Comment by Notsfsssf** [comment]
我是用`save_in_gallery`这个plugin来实现保存的，没有系统的学习过ios开发，不过能解决了就好
