### ISSUE TITLE
最近使用得挂梯子才能看到图片了

### ISSUE THREAD

**Issue by Ziziru** [Notsfsssf/pixez-flutter#133]
上个月还是正常使用，最近发现已经没法裸连，都要挂梯子才能看到内容，移动宽带和联通的4G流量都不行

报错 DioError [DioErrorType.Default]: SocketException: OS Error: Connection refused, errno = 111,address=210.140.131.188, port每次刷新都在变

**Comment by ygsk10** [comment]
更新

**Comment by Notsfsssf** [comment]
更新一下吧。。。你这个是老版本的问题

**Comment by Ziziru** [comment]
确实，更新就解决问题了，谢谢
