### ISSUE TITLE
0.34版图片加载全部失败，只能挂vpn用

### ISSUE THREAD

**Issue by Sunkenseas** [Notsfsssf/pixez-flutter#135]

**Comment by liuxinyu970226** [comment]
我这边的话，wifi图片加载失败，流量正常

**Comment by Sunkenseas** [comment]
我是流量wifi都不行，正常都是用流量，不行了试一下wifi，没有改观qwq 在2021年02月08日 06:11，Liu Xin Yu 写道： 我这边的话，wifi图片加载失败，流量正常 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by WarnError** [comment]
> 我是流量wifi都不行，正常都是用流量，不行了试一下wifi，没有改观qwq 在2021年02月08日 06:11，Liu Xin Yu 写道： 我这边的话，wifi图片加载失败，流量正常 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

或许是你Hosts文件的问题

**Comment by Sunkenseas** [comment]
不会改呀 在2021年02月08日 19:16，WarnError 写道： 我是流量wifi都不行，正常都是用流量，不行了试一下wifi，没有改观qwq 在2021年02月08日 06:11，Liu Xin Yu 写道： 我这边的话，wifi图片加载失败，流量正常 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 或许是你Hosts文件的问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liuxinyu970226** [comment]
@Sunkenseas 会root么，root完以后装RE浏览器

**Comment by Sunkenseas** [comment]
不会，但可以学 在2021年02月09日 07:55，Liu Xin Yu 写道： @Sunkenseas 会root么，root完以后装RE浏览器 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
