### ISSUE TITLE
Apple store里面这个软件下架了吗？

### ISSUE THREAD

**Issue by zuiwuguigui** [Notsfsssf/pixez-flutter#136]

**Comment by Skimige** [comment]
中国区被下架，日区未上架，使用其他区账号可正常下载。

**Comment by liuxinyu970226** [comment]
要不给个ipa下载地址，至少越狱控可以用吧

**Comment by zuiwuguigui** [comment]
我试了下改苹果id改成美区，能搜到，但是不知道更新可不可用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu Xin Yu"<notifications@github.com&gt;; 
发送时间: 2021年2月8日(星期一) 上午6:09
收件人: "Notsfsssf/pixez-flutter"<pixez-flutter@noreply.github.com&gt;; 
抄送: "文赢盛"<1348970900@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Notsfsssf/pixez-flutter] Apple store里面这个软件下架了吗？ (#136)





 
要不给个ipa下载地址，至少越狱控可以用吧
