### ISSUE TITLE
关于从「相关图片」进入图片页时的滑动交互建议

### ISSUE THREAD

**Issue by JetLiu233** [Notsfsssf/pixez-flutter#143]
希望添加通过某一插图页底部的「相关图片」板块进入插图页后，可以通过滑动交互查看下一张/上一张推荐插图，使浏览可以更连贯

如图
![S10212-21045950(1)](https://user-images.githubusercontent.com/63274744/107773726-0a86aa00-6d79-11eb-8ad4-7d029becd1af.png)
![S10212-21050175(1)](https://user-images.githubusercontent.com/63274744/107773717-078bb980-6d79-11eb-86c4-600186eefeb3.png)
![S10212-21051064(1)](https://user-images.githubusercontent.com/63274744/107773710-0490c900-6d79-11eb-874e-1357ba49e8ba.png)

非常感谢

**Comment by Notsfsssf** [comment]
那么滑动下一张插画得放在哪儿呢

**Comment by JetLiu233** [comment]
嗯抱歉…我不是很能理解您「得放在哪儿」的意思…？
其实就是像从每日榜单、首页推荐或者搜索查看插画的时候，通过滑动可以进入下一张插图的页面那样，在相关图片这个模块上也做一个这样的交互
像现在这样的话，就必须要回退到上一个页面才能点选下一张相关插画，让浏览没有那么连贯，但不知为什么很多第三方客户端都没有做这个原生客户端和网页端就有的交互

感谢您抽出时间回复

**Comment by JetLiu233** [comment]
> 那么滑动下一张插画得放在哪儿呢

嗯抱歉…我不是很能理解您「得放在哪儿」的意思…？
其实就是像从每日榜单、首页推荐或者搜索查看插画的时候，通过滑动可以进入下一张插图的页面那样，在相关图片这个模块上也做一个这样的交互
像现在这样的话，就必须要回退到上一个页面才能点选下一张相关插画，让浏览没有那么连贯，但不知为什么很多第三方客户端都没有做这个原生客户端和网页端就有的交互

感谢您抽出时间回复

**Comment by Notsfsssf** [comment]
已实现，下一个版本更新

**Comment by JetLiu233** [comment]
辛苦了，非常感谢
