### ISSUE TITLE
路径/storage/emulated/0/Pictures/Pixiv不存在时无法保存图片

### ISSUE THREAD

**Issue by metase** [Notsfsssf/pixez-flutter#148]
删除Pixiv文件夹后保存图片，pixiv文件夹不会生成。下载队列完成后不会保存到设备

**Comment by Notsfsssf** [comment]
如果是saf授权，授权时拿到的是/Pictures/Pixiv的授权，并不是/或者/Pictures，也就没有权力在/Pictures创建Pixiv文件夹
