### ISSUE TITLE
暗黑主题下的下方导航栏变白色了

### ISSUE THREAD

**Issue by austinhuang0131** [Notsfsssf/pixez-flutter#152]
![2b62583f-60d2-422f-a61d-346c470c0cf5](https://user-images.githubusercontent.com/16656689/108945888-71367e00-762b-11eb-9a42-d02000105b44.jpg)

0.3.9 BRAVO, Android 9

p.s. AMOLED开着但似乎没用(除更多页面外)

**Comment by austinhuang0131** [comment]
Fixed in 0.4.0 Lotus

**Comment by Notsfsssf** [comment]
本意是把内容沉浸到导航栏以下，但是似乎很多系统呈现出了不同的风格，所以0.4.0取消了
