### ISSUE TITLE
评论栏会遮挡最后一个评论

### ISSUE THREAD

**Issue by xiaozixun** [Notsfsssf/pixez-flutter#161]
![Screenshot_20210304_162031_com perol pixez](https://user-images.githubusercontent.com/22409452/109934264-47eeaf80-7d07-11eb-9988-f05f9b368d7d.jpg)

如图，我的手机是华为mate 20

**Comment by xiaozixun** [comment]
还有两个功能希望实现：收藏时能否编辑；改变下下载方式（我因为个人使用习惯有时会长按屏幕不操作，这就导致app会自动下载）。

**Comment by Notsfsssf** [comment]
已修复
