### ISSUE TITLE
Url scheme设置错误导致ios端无法通过url打开

### ISSUE THREAD

**Issue by zhihaofans** [Notsfsssf/pixez-flutter#165]
ios的Info.plist里设置的是`pixiez`，但是Android的`AndroidManifest`和Dart代码里却是`pixez`

具体位置：

- [Info.plist](https://github.com/Notsfsssf/pixez-flutter/blob/648a03d91251587524f209ad9ffa4ea666aa24d6/ios/Runner/Info.plist#L36)
- [AndroidManifest.xml](https://github.com/Notsfsssf/pixez-flutter/blob/b7dfb94348dfae11f7fcb866e1ec97940ca15544/android/app/src/main/AndroidManifest.xml#L76)
- [Dart代码](https://github.com/Notsfsssf/pixez-flutter/blob/0c63b7d9b39acef955e843e274345a1ca59e36b7/lib/er/leader.dart#L68)

不会flutter，Url scheme相关代码应该是这几个文件

**Comment by Notsfsssf** [comment]
已修复
