### ISSUE TITLE
使用mediastore方式保存时会卡死闪退

### ISSUE THREAD

**Issue by DongGuaGH** [Notsfsssf/pixez-flutter#167]
更新版本之后存图会卡死闪退
后发现是改用mediastore方式储存图片引起的
曾试过清除缓存，清除数据均无效
改用传统方式后不会闪退

app版本:
版本 0.4.3 Impl
Google play版

手机信息:
一加7pro
氧OS 安卓11 beta3

**Comment by DongGuaGH** [comment]
![Screenshot_20210318-172929__01](https://user-images.githubusercontent.com/26429772/111604195-0df5d100-8810-11eb-8155-10136deb8bac.jpg)
附上无响应时的一些信息
另外我发现两次返回退出功能也失效了

**Comment by Notsfsssf** [comment]
已修复
