### ISSUE TITLE
这个画师全是R-18作品，但app里不显示R-18

### ISSUE THREAD

**Issue by liuxinyu970226** [Notsfsssf/pixez-flutter#168]
https://www.pixiv.net/users/66111544

自己试吧，不敢贴截图，怕违反Github使用条款

**Comment by Notsfsssf** [comment]
自己账号的问题自己去官网开开关

**Comment by 2901824193** [comment]
解决了，谢谢发自我的华为手机-------- 原始邮件 --------发件人： Perol_Notsfsssf ***@***.***>日期： 2021年3月19日周五 傍晚6:32收件人： Notsfsssf/pixez-flutter ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [Notsfsssf/pixez-flutter] 这个画师全是R-18作品，但app里不显示R-18 (#168)

自己账号的问题自己去官网开开关
