### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by xiaozixun** [Notsfsssf/pixez-flutter#170]
1.希望在收藏时能编辑标签；
2.搜索时能像网页一样区分r-18和全部；
3.改变下下载方式（我因为个人使用习惯有时会长按屏幕不操作，这就导致app会自动下载）。

**Comment by 2901824193** [comment]
333332发自我的华为手机-------- 原始邮件 --------发件人： xiaozixun ***@***.***>日期： 2021年3月19日周五 下午2:02收件人： Notsfsssf/pixez-flutter ***@***.***>抄送： Subscribed ***@***.***>主    题： [Notsfsssf/pixez-flutter] 几个建议 (#170)

1.希望在收藏时能编辑标签；

2.搜索时能像网页一样区分r-18和全部；

3.改变下下载方式（我因为个人使用习惯有时会长按屏幕不操作，这就导致app会自动下载）。
