### ISSUE TITLE
建议修改回复时间、回复对象的字体颜色

### ISSUE THREAD

**Issue by nothingshiru** [Notsfsssf/pixez-flutter#177]
为了方便区别哪些是评论正文，建议把“to 用户名”和回复时间的字体颜色改一下，然后在“to 用户名”和评论正文之间加一行间距。

目前很容易混在一起
![Screenshot_20210326_130128_com perol pixez](https://user-images.githubusercontent.com/79258245/112584950-dc928c00-8e33-11eb-8ac5-5005a022f3a1.jpg)

**Comment by Notsfsssf** [comment]
有道理

**Comment by nothingshiru** [comment]
还有，可不可以把这种“楼中楼”移动到被回复的评论的下边呀？
现在所有评论都是按时间排序，就总是先看到“楼中楼”，然后往下滑才看到他们所评论的“楼层”到底说了什么

**Comment by EmptyDreams** [comment]
> 有道理

现在回复功能是坏的，别人回复的时候显示正常，但是自己点回复按钮回复别人的时候和直接发评论没区别
