### ISSUE TITLE
无法显示关注画师列表

### ISSUE THREAD

**Issue by ziyu-king** [Notsfsssf/pixez-flutter#185]
版本0.4.7 los 无法显示关注画师
速览-已关注 个人页面-关注均无法显示关注画师列表（空白页面）
![Screenshot_2021-04-26-23-35-43-080_com perol play pixez](https://user-images.githubusercontent.com/60423212/116110313-29de7380-a6e8-11eb-92ba-f56963e8462e.jpg)
![Screenshot_2021-04-26-23-35-39-017_com perol play pixez](https://user-images.githubusercontent.com/60423212/116110325-2c40cd80-a6e8-11eb-9f11-c45e8fa8d31c.jpg)

**Comment by Notsfsssf** [comment]
已修复
