### ISSUE TITLE
长按APP图标导致启动器崩溃

### ISSUE THREAD

**Issue by sr1canskhsia** [Notsfsssf/pixez-flutter#187]
安卓版本：10
APP版本：0.4.8
启动器：Lawnchair Version 10.0 Alpha 8

预期行为：长按APP图标应显示应用快捷方式
实际行为：Lawnchair崩溃

其他的APP长按图标都没有问题，就PixEz会导致启动器崩溃
以前好像不会崩溃的，不知道从哪个版本开始就这样了

[Lawnchair bug report Apr. 27, 2021 11_34_01.txt](https://github.com/Notsfsssf/pixez-flutter/files/6381678/Lawnchair.bug.report.Apr.27.2021.11_34_01.txt)

**Comment by Notsfsssf** [comment]
似乎是因为lawnchair没有资源检测机制，拿不到resource直接抛异常
下个版本打算去掉暂时没啥乱用的short cut功能，应该就没问题了
