### ISSUE TITLE
iOS版在中国区App Store不可用

### ISSUE THREAD

**Issue by AmemiyaAkira** [Notsfsssf/pixez-flutter#190]
![8ACFED0663894128BD0742AC86693FEC](https://user-images.githubusercontent.com/56263990/116548732-41576f80-a927-11eb-980d-22362eb263b5.png)
like this pic, 今天突然有人告诉我不能用了，一看。。

**Comment by Notsfsssf** [comment]
国区被gov要求下架了，你可以在非日区，非国区下载到，登录没有直连了，登录后有

**Comment by liuxinyu970226** [comment]
> 国区被gov要求下架了，你可以在非日区，非国区下载到，登录没有直连了，登录后有

要不给个Y U E Y U控喜欢的deb包？
