### ISSUE TITLE
想问一下是否有桌面版本计划

### ISSUE THREAD

**Issue by GoFly233** [Notsfsssf/pixez-flutter#191]
Flutter 是个跨平台的框架，想问一下有没有可能对「Windows」，「macOS」和「Linux」等桌面平台做适配？

**Comment by Notsfsssf** [comment]
目前适配问题比较多
三个method channel需要编写，一个是加密库的，一个是接收pixiv://的，一个是存图的
需要一个适合大屏的Navigator首页，另外字体渲染用系统默认字体也不太行
直接添加倒是跑的起来，我在windows和macos上测试过，扫地机器人在arch上也跑过，欢迎PR
