### ISSUE TITLE
直连登录还能实现吗？

### ISSUE THREAD

**Issue by OpenG8** [Notsfsssf/pixez-flutter#192]
如题

**Comment by sunbeams001** [comment]
不能完美实现吧，域前置原理还可以用
似乎是登录页面的谷歌验证码有点问题？一旦遇到就加载不出

**Comment by Notsfsssf** [comment]
勉强可用的状态，我这边联通是没啥问题 ，就是移动卡的用户经常反馈说不行
没辙了，我也没有移动卡
人机验证的话看运气
