### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rijan72** [Notsfsssf/pixez-flutter#193]
Thank you for this app. It's really smooth and better then the official app in all aspect.

The only downgrade is that there is no option to view and edit the bookmarked tags of pictures you have already liked.
 In pixiv app you do this by holding the love button.

Please add a option to view and edit bookmarked picture tags.🙏

Thank you for your kind time.

**Comment by Notsfsssf** [comment]
Just long press the favorite icon should be able to see this function :)

**Comment by rijan72** [comment]
Long pressing only works if you have not liked the pictures. 

If you have liked the pictures it doesn't bring the edit tags view rather it dislikes the image.

https://user-images.githubusercontent.com/34618572/116782395-8d7ded80-aaa8-11eb-8948-81ba1e884cd0.mp4

**Comment by rijan72** [comment]
https://user-images.githubusercontent.com/34618572/116802582-87811e80-ab33-11eb-9512-79d65748f68e.mp4

**Comment by rijan72** [comment]
Thank you for having enabling this feature in the latest update. ❤️
