### ISSUE TITLE
这个appstore显示所在地区不可用

### ISSUE THREAD

**Issue by Tanulav** [Notsfsssf/pixez-flutter#200]
rt，国服和日服都试过了

**Comment by Notsfsssf** [comment]
只有这俩区没有，其他都有

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年5月7日 13:43
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Notsfsssf/pixez-flutter] 这个appstore显示所在地区不可用 (#200)


rt，国服和日服都试过了

―

**Comment by Tanulav** [comment]
好的，我再去试试
