### ISSUE TITLE
剪切板问题

### ISSUE THREAD

**Issue by zhao141** [Notsfsssf/pixez-flutter#223]
请问是用了什么sdk吗？怎么一直在读取我的剪切板，一分钟读取40多次，我这一次都还没使用搜索呢。

**Comment by Notsfsssf** [comment]
如果你有能力的话，可以去flutter官网，用官方示例，把`Text`改成`SelectableText`，你会发现编译完成后打开应用就提示访问剪切板，或者有剪切板读取的记录，这不是我的问题，我觉得这是检测的问题
如果这对于你来说太难了，可以前往下载 [flutter gallery](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en)，google官方搞的示例app，反复打开`文本字段`这一项，看看所谓的剪切板读取是不是记录了多次，官方的app都被检测成这样，我的app有什么办法呢

一个可选择的文本的控件，每次实例化都要某系统被记录为访问剪切板，我怎么避免？我不让用户选择插画id吗

https://api.flutter.dev/flutter/material/SelectableText-class.html
