### ISSUE TITLE
蓝奏云文件有误

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#225]
蓝奏云里面的安装包写的是0.5.5，安装后却为0.5.4

**Comment by Steve-cn** [comment]
github里面下载的也是这样……算是一个小bug吧，在应用管理界面里面版本号是正确的

**Comment by EmptyDreams** [comment]
> github里面下载的也是这样……算是一个小bug吧，在应用管理界面里面版本号是正确的

但是我从gh下的安上去就是0.5.5了

**Comment by Steve-cn** [comment]
> > github里面下载的也是这样……算是一个小bug吧，在应用管理界面里面版本号是正确的
> 
> 但是我从gh下的安上去就是0.5.5了

我gh上下载，软件详情里面是0.5.5，但软件里面仍然是0.5.4，并提示有新版
![Screenshot_2021-07-01-15-43-39-825_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/48684035/124086061-48177580-da83-11eb-905f-2a4a96adb2c5.jpg)
![Screenshot_2021-07-01-15-43-55-962_com.perol.pixez.jpg](https://user-images.githubusercontent.com/48684035/124086084-4d74c000-da83-11eb-823d-18fe1c6f1e86.jpg)

**Comment by EmptyDreams** [comment]
> > > github里面下载的也是这样……算是一个小bug吧，在应用管理界面里面版本号是正确的
> > 
> > 
> > 但是我从gh下的安上去就是0.5.5了
> 
> 我gh上下载，软件详情里面是0.5.5，但软件里面仍然是0.5.4，并提示有新版
> ![Screenshot_2021-07-01-15-43-39-825_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/48684035/124086061-48177580-da83-11eb-905f-2a4a96adb2c5.jpg)
> ![Screenshot_2021-07-01-15-43-55-962_com.perol.pixez.jpg](https://user-images.githubusercontent.com/48684035/124086084-4d74c000-da83-11eb-823d-18fe1c6f1e86.jpg)

emm..我是蓝奏云下载下来这样，但是gh下载下来正常

**Comment by Steve-cn** [comment]
> > > > github里面下载的也是这样……算是一个小bug吧，在应用管理界面里面版本号是正确的
> > > 
> > > 
> > > 但是我从gh下的安上去就是0.5.5了
> > 
> > 我gh上下载，软件详情里面是0.5.5，但软件里面仍然是0.5.4，并提示有新版
> > ![Screenshot_2021-07-01-15-43-39-825_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/48684035/124086061-48177580-da83-11eb-905f-2a4a96adb2c5.jpg)
> > ![Screenshot_2021-07-01-15-43-55-962_com.perol.pixez.jpg](https://user-images.githubusercontent.com/48684035/124086084-4d74c000-da83-11eb-823d-18fe1c6f1e86.jpg)
> 
> emm..我是蓝奏云下载下来这样，但是gh下载下来正常

刚刚又试了一下，的确正常了，可能是已经修复了，之前的确是有这个问题，蓝奏云可能没更新

**Comment by Notsfsssf** [comment]
各位不用纠结这个了，的确是我忘了改version name，一直是手改的，flutter那边的flavor做了变动忘记了，这星期会发一个新版顺带更正的
