### ISSUE TITLE
已支持。关于屏蔽功能的建议。

### ISSUE THREAD

**Issue by PYUDNG** [Notsfsssf/pixez-flutter#226]
尽管数字实在不够看，但还是通过微信支持了此项目
![4691624439995_ pic](https://user-images.githubusercontent.com/63054558/123071724-7d9ade00-d447-11eb-99fb-83cbb4100856.jpg)

接下来是有关屏蔽功能的改进建议：
这是屏蔽页面：
![1001624440076_ pic_hd](https://user-images.githubusercontent.com/63054558/123073085-b12a3800-d448-11eb-84f1-8719ab3c62a2.jpg)
可以看到，只有三个按钮：返回，屏蔽设定，收藏
首先是这个收藏按钮，插画都已经屏蔽了，为什么还会收藏呢？无意义
然后是屏蔽设定按钮，点进去是这样的：
![1011624440418_ pic_hd](https://user-images.githubusercontent.com/63054558/123073086-b12a3800-d448-11eb-812c-bb5a1dfa20a8.jpg)
密密麻麻的都是标签（而且都是我不想看到的标签），而我根本不知道和这张插画有关的标签到底是哪些
那么这会导致什么不方便之处呢？
比如我认为这张插画是误屏蔽的，想要暂时查看或者解除屏蔽，很可惜没有任何一个按钮让我能临时查看这张插画，没有一个提示告诉我和这张插画有关的屏蔽标签是什么，也没有一个按钮能够解除屏蔽；只能点进屏蔽设定，面对着密密麻麻的一大堆我不想看到的标签，一个个的去猜…

希望可以有所改进。谢谢Notsfsssf。
PS：屏蔽标签页的内容实在是太恶心了，打了个码，希望不要介意（说白了就是不想暴露XP）

**Comment by Notsfsssf** [comment]
确实需要改进，会在后续版本加入的
