### ISSUE TITLE
两个bug

### ISSUE THREAD

**Issue by PYUDNG** [Notsfsssf/pixez-flutter#230]
麻雀虽小，五脏俱全
bug虽小，确实存在

一张图片说明一切
![4741624599856_ pic_hd](https://user-images.githubusercontent.com/63054558/123375512-74328280-d5bb-11eb-86f9-03ffd2d55ab7.jpg)
首先要说明，我已更新到了最新版0.5.5
所以，第一个bug就是：你忘记增加版本号了。。

然后请看上面的Contributors一栏
看上去没问题对吧
但是仔细观察会发现，每个contributor底下的图标（不是头像，是底下的图标）没有对齐

就是这两个木有什么卵用的bug。
以上。

**Comment by RxinnotRstar** [comment]
那个是emoji表情，是文本框的锅。
你把字体调小就可以了
