### ISSUE TITLE
Android11 导航栏无法沉浸

### ISSUE THREAD

**Issue by guoyanhuyun** [Notsfsssf/pixez-flutter#231]
![Screenshot_20210626-180448](https://user-images.githubusercontent.com/54035040/123509626-1ed49f00-d6a9-11eb-932e-e74b90a61769.png)
如图所示，小白条无法随主题变色，都是黑的啊😭

**Comment by Notsfsssf** [comment]
适配过一版，结果是pixel白miui黑，于是就放弃了，搞不来这种

**Comment by guoyanhuyun** [comment]
啊这。。。😂

**Comment by guoyanhuyun** [comment]
要不然老哥做个按钮开关？有的机型正常就用户自己开启，不正常就关闭这个样子的。(主要是底栏小白条不适配好难看啊😭老哥考虑一下看看行不行哈！)
