### ISSUE TITLE
[功能建议] 增加更改doh的选项

### ISSUE THREAD

**Issue by zzh-blog** [Notsfsssf/pixez-flutter#233]
正常情况
![Screenshot_2021-07-07-15-50-25-687_app intra](https://user-images.githubusercontent.com/36284614/124721788-00d62c80-df3c-11eb-999e-600fc23cba6d.jpg)

![Screenshot_2021-07-07-15-52-03-463_com perol pixez](https://user-images.githubusercontent.com/36284614/124721121-6970d980-df3b-11eb-8274-bddeebcc133c.jpg)

用Intra代理了doh服务后

![Screenshot_2021-07-07-15-52-21-137_app intra](https://user-images.githubusercontent.com/36284614/124721112-67a71600-df3b-11eb-8204-c889dcfbd9a2.jpg)

![Screenshot_2021-07-07-15-52-34-993_com perol pixez](https://user-images.githubusercontent.com/36284614/124721095-64ac2580-df3b-11eb-99a3-796712c105f5.jpg)

查阅代码之后发现，似乎是程序内部使用的doh服务固定为1.0.0.1的原因。

希望能增加一个更改doh服务地址的选项。

ps: 腾讯的那个公开的doh服务挺好用的

**Comment by Notsfsssf** [comment]
如果国内的doh服务稳定就好了，周末看看

**Comment by Notsfsssf** [comment]
经过测试，腾讯的doh指向了错误的地址   
国内应该没有服务商会提供未被污染过的doh服务，你可以自己试试解析出的地址是哪儿

**Comment by Notsfsssf** [comment]
```
https://doh.pub/dns-query?name=app-api.pixiv.net&type=A
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"app-api.pixiv.net.","type":1}],"Answer":[{"name":"app-api.pixiv.net.","type":1,"TTL":180,"Expires":"Sat, 10 Jul 2021 10:05:01 UTC","data":"74.86.12.173"}],"edns_client_subnet":"123.115.79.190/24"}
```

**Comment by zzh-blog** [comment]
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"app-api.pixiv.net.","type":1}],"Answer":[{"name":"app-api.pixiv.net.","type":1,"TTL":213,"Expires":"Sat, 10 Jul 2021 11:33:44 UTC","data":"31.13.64.33"}],"edns_client_subnet":"112.20.68.248/24"}

**Comment by zzh-blog** [comment]
江苏省南京市 移动 -> 荷兰 北省阿姆斯特丹utc+1数据中心

**Comment by Notsfsssf** [comment]
> 江苏省南京市 移动 -> 荷兰 北省阿姆斯特丹utc+1数据中心

31.13.64.33就是被污染的ip。。

**Comment by zzh-blog** [comment]
!

**Comment by Notsfsssf** [comment]
> ! ?

你可以自己找找dns污染常见解析到的api，我记得有人专门列出来过，这个31开头的明显就是，pixiv是210开头的才是正确的

**Comment by Notsfsssf** [comment]
去年还是哪个时候开始我决定用doh动态获得ip的时候就测试过一圈，我给忘了，当时就只有1001合适又能访问，只记得阿里的也是被污染的，如果没有新的发现的话，可以close这个议题了

**Comment by zzh-blog** [comment]
可以向根服务器发送请求 https://www.iana.org/domains/root/servers，这个网站包含一个互联网根域名服务器的列表。

我刚刚测试了一下，解析的数据会不断的改变（？）有过几个返回的ip是在我现在的所在地可以正常解析（Nginx反代）app-api.pixiv.net的

测试列表：
|响应IP|TTL值|
|-|-|
|103.97.176.73 [亚太地区 ] |221|
|||
|||
|||

**Comment by zzh-blog** [comment]
好多ip似乎无法访问，我后天研究一下。
