### ISSUE TITLE
无法登陆，页面提示网页无法打开

### ISSUE THREAD

**Issue by dieterminator** [Notsfsssf/pixez-flutter#235]
![Screenshot_2021-07-10-20-25-08-478_PixEz](https://user-images.githubusercontent.com/52268813/125162902-ff676700-e1bc-11eb-8239-ac54182ef3b2.png)
尝试在电信宽带网络 和 联通移动网络下链接过，结果依旧如上截图所示
使用的是0.5.6版本

**Comment by huangguiniab** [comment]
登录请先翻墙，目前*.pixiv.net所有子域均被阻断，登录暂时不能免翻墙登录，以前只是DNS污染，改个dns就行。现在直接就是SNI阻断，只要嗅探到你的流量里有*.pixiv.net字段就直接抛弃你的数据包，所以现在没有解决方案

**Comment by dieterminator** [comment]
我尝试使用ssr在俄罗斯节点下，依旧出现无法访问的问题 〒▽〒
