### ISSUE TITLE
建议 iOS 平台显示 Sanity Single Folder 开关

### ISSUE THREAD

**Issue by ddddbug** [Notsfsssf/pixez-flutter#236]
相关的改动可能有:

1.
https://github.com/Notsfsssf/pixez-flutter/blob/30654eb16ef6c3675a52be102b3f60cd00da329d/lib/store/save_store.dart#L242-L247

改成

```
    } else {
      final _imageSaver = ImageSaver();
      List<Uint8List> bytesList = [uint8list];
      if (userSetting.overSanityLevelFolder && sanityLevel > 2) {
        await _imageSaver.saveImages(
            imageBytes: bytesList, directoryName: 'pxez_sanity');
      } else {
        await _imageSaver.saveImages(
            imageBytes: bytesList, directoryName: 'pxez');
      }
    }
```

2.

https://github.com/Notsfsssf/pixez-flutter/blob/8549922d351e91cdb8d2d67658a4530f3cc0e902/lib/page/platform/platform_page.dart#L155-L166

换到上个设置视图？

不会写 Dart ，所以第二个改动不太清楚，没敢提 PR 。
望采纳。

**Comment by Notsfsssf** [comment]
主要担心的是`Sanity level `在ios审核眼里是不是就不该存在，毕竟是明面上完全杜绝性暗示，可以尝试挑战一下。。

**Comment by ddddbug** [comment]
不过 App Store 里面已经[标明](https://apps.apple.com/us/app/pixez/id1494435126)了

> Age Rating
> 17+
> Infrequent/Mild Mature/Suggestive Themes
> Frequent/Intense Sexual Content or Nudity 

当然，我也不是很懂 iOS 怎么审核的...

**Comment by Notsfsssf** [comment]
> 不过 App Store 里面已经[标明](https://apps.apple.com/us/app/pixez/id1494435126)了
> 
> > Age Rating
> > 17+
> > Infrequent/Mild Mature/Suggestive Themes
> > Frequent/Intense Sexual Content or Nudity
> 
> 当然，我也不是很懂 iOS 怎么审核的...

google play是标成18+连紧身衣都不能有，ios app store估计更甚吧，不过我可以试试，app store遇到不适合的更新只会打回，不会像google play一样封禁应用

**Comment by ddddbug** [comment]
懂了，所以如果为了闪避可以换个名字？

**Comment by Notsfsssf** [comment]
已添加
