### ISSUE TITLE
可否放在f-droid或者izzyondroid上？

### ISSUE THREAD

**Issue by OliverLew** [Notsfsssf/pixez-flutter#237]
不知道是否符合fdroid的要求，izzyondroid要求更松一些。

放下fdroid仓库里，安装和更新更方便。

**Comment by Notsfsssf** [comment]
Fdroid较为复杂，因为flutter 对sdk版本比较敏感，然后他是自签名的，拉repo给他编译，就是说上了的话会把用户割成三部分，play的，普通的，fdroid的，还是算了吧

**Comment by OliverLew** [comment]
fdroid很多应用都是和谷歌商店一同上架的。当然，你说的flutter的问题，我就完全不了解了，我不熟悉安卓开发。那我就关掉issue了，如果有变化的话，也可以重开。

**Comment by linsui** [comment]
F-Droid 里有大量 Flutter 应用，编译和更新不会存在问题。至于用户不能互相在几个来源之间相互切换的问题，只能通过可重复构建解决，不过难度很大，基本不可能实现。如果你不介意这个问题，我会做余下的提交工作。

**Comment by Notsfsssf** [comment]
> F-Droid 里有大量 Flutter 应用，编译和更新不会存在问题。至于用户不能互相在几个来源之间相互切换的问题，只能通过可重复构建解决，不过难度很大，基本不可能实现。如果你不介意这个问题，我会做余下的提交工作。
我关心的是，是否会有开发者能长期维护FDroid配置相关的代码
毕竟flutter一直在迭代，FDroid的相关配置也需要长期维护跟进，特别是build runner那边的，自动化构建已经有贡献者fork里实现了，我也没精力管三头了，上架一次就完事了那还不如不上架  
还有就是用户分裂问题，三个端不同签名，出问题全是反馈到我的，如果是FDroid那边滞后了又会是非常麻烦的事情

**Comment by linsui** [comment]
构建失败需要更新 Flutter 版本之类的问题 F-Droid 的开发者会去解决的，如果有更复杂难以解决的问题会反馈给你们。用户分裂的问题就比较难以解决了。

**Comment by UjuiUjuMandan** [comment]
一个月前Izzy接受了: https://gitlab.com/IzzyOnDroid/repo/-/issues/462 .

**Comment by linsui** [comment]
顺便一说，目前 F-Droid 上已经有不少可重复构建的 Flutter 应用了。

**Comment by UjuiUjuMandan** [comment]
可以Reproducible Builds的话，F-Droid就相当于从 GitHub Releases 爬 APK 再分发了，相当于 GitHub 版本多了一个渠道而已。不过 GitHub 版本和 Play 有何区别？

**Comment by UjuiUjuMandan** [comment]
版本真乱...
