### ISSUE TITLE
圖像保存報錯，自動退出軟件

### ISSUE THREAD

**Issue by tree23333** [Notsfsssf/pixez-flutter#239]
本人小米10 海外版MIUI12.2.5
保存圖像時常報錯，并自動退出
祇有清除緩存并重啟軟件方可解決
真的麻煩，求大佬解決QWQ

**Comment by Notsfsssf** [comment]
是以什么方式保存图片的呢
应用内提供了三种方式，第一种是直接往pictures里写，
第二种是saf，授权很麻烦但是是在target 30情况下存任意目录的唯一解，且授权之后如果文件夹被删除就需要重新授权，授权一旦出问题就可能会导致闪退
第三种是传统模式，只适用于android9以下
