### ISSUE TITLE
Operation not permitted 

### ISSUE THREAD

**Issue by baraa272** [Notsfsssf/pixez-flutter#249]
我面临着一个非常新的错误和一个新的问题
当我尝试下载图像时，下载挂在最后，我得到了一个。错误消息（不允许操作），之后应用程序粉碎
下面是截图
![Screenshot_2021-08-21-04-20-03-257_com perol pixez](https://user-images.githubusercontent.com/32843097/130306118-881f6c18-e24a-49d1-9825-e7ac63803fd7.jpg)

**Comment by Notsfsssf** [comment]
已修复，尝试更新到0.6.1
