### ISSUE TITLE
关于一直读取剪切板的问题

### ISSUE THREAD

**Issue by blycr** [Notsfsssf/pixez-flutter#253]
红米手机，在有输入框检索图片或者进去图片详情页的时候，一直提示读取剪切板上百次，每次读取10下
![Screenshot_2021-08-29-02-13-59-051_com perol pixez](https://user-images.githubusercontent.com/87604710/131227072-319b669b-704a-460a-8174-00afb92b27ad.jpg)
如果不退出这个界面会一直读取

**Comment by blycr** [comment]
这个问题一直就有，不是最近版本才出现的

**Comment by Notsfsssf** [comment]
这个没得解决，你可以前往flutter官网，拿他的demo，把`Text`改成`SelectableText`，然后你会发现miui报读取剪切版
#223
