### ISSUE TITLE
1.6.1 iOS 尚未解决自定义图床于下载无效的问题

### ISSUE THREAD

**Issue by love4taylor** [Notsfsssf/pixez-flutter#254]
当指定图床之后，预览图片的时候是正常使用该地址的，但进行下载操作的时候却是 Pixiv 的 IP 加上指定图床的 Host（使用 Surge MitM 且验证证书就能发现）。我认为当我自定义图床域名时就是为了躲过封锁，但是下载时却依旧使用 Pixiv 的 IP 岂不是白搞？（当我网络只是 gfwlist 的话就无法连通）

![B7EF6D39-8E15-48C9-A562-716B7E494E35](https://user-images.githubusercontent.com/6081912/131235437-b651a78a-6063-4ae3-902a-7b8149de7d93.jpeg)
![F30287AD-F874-4F27-A16E-95857559DA05](https://user-images.githubusercontent.com/6081912/131235440-e879a923-409d-4001-8d0f-fae1e836de7e.jpeg)
![9E0196EF-195C-40C8-9BDC-1D08B6ABB3F4](https://user-images.githubusercontent.com/6081912/131235441-fca10ce2-e006-426d-8043-770504aa8111.jpeg)
![1EC4AA1B-2E65-4AB1-9E7E-3150BE89F76E](https://user-images.githubusercontent.com/6081912/131235442-86d4729d-410c-47f8-aec0-6d74e7eaeb94.jpeg)

**Comment by Notsfsssf** [comment]
最开始用isolate的时候我记得是解决过一次，后来不知道怎么的bug又冒出来了
这东西麻烦之处就在于，使用官方的图床有的地区会需要检查一下真实ip然后才能用，有的地区用真实ip也不能用，只能用cat
但是这俩情况在应用的实现会不同，没仔细设计过，所以代码乱糟糟的
应该是代码逻辑有问题，下个版本改了

**Comment by love4taylor** [comment]
没问题了
