### ISSUE TITLE
安卓平板闪退

### ISSUE THREAD

**Issue by Gurewitte** [Notsfsssf/pixez-flutter#262]
用平板打开软件正常，但是点登入时就会闪退
平板系统是安卓10，是系统太老的原因吗？
![Screenshot_20210925-023027](https://user-images.githubusercontent.com/91344645/134726181-e307abfe-0d0c-4653-abbf-da2b8a1007d9.png)

**Comment by Notsfsssf** [comment]
似乎是系统webview的问题
