### ISSUE TITLE
图片等均无法加载，且切换网络也无效

### ISSUE THREAD

**Issue by hezhen10** [Notsfsssf/pixez-flutter#263]
![Screenshot_20210925_102359_com perol pixez](https://user-images.githubusercontent.com/91356635/134754756-b4fcb481-63b3-4906-a5e4-548ce8d35a36.jpg)
![Screenshot_20210925_101422_com perol pixez](https://user-images.githubusercontent.com/91356635/134754722-aef9e5f1-9f5d-4e42-a96d-f2a6e08c651a.jpg)

![Screenshot_20210925_102356_com perol pixez](https://user-images.githubusercontent.com/91356635/134754754-cd512988-0252-4d85-adbe-90cec90f107c.jpg)

**Comment by hezhen10** [comment]
主要问题在第二张图，也就是101422的内一张

**Comment by Notsfsssf** [comment]
400是身份信息错误
前往官网
检查账号密码密码是否有变更
账户是否被封禁
所用ip是否被封禁

**Comment by hezhen10** [comment]
好的，谢谢

**Comment by hezhen10** [comment]
另外再多说一句，多谢大佬啊(*๓´╰╯`๓)♡
