### ISSUE TITLE
登陆时ReCAPTCHA验证失败

### ISSUE THREAD

**Issue by myf2001** [Notsfsssf/pixez-flutter#274]
如题，ReCAPTCHA验证时可以正常加载验证图片，但一直显示“请重试”。

**Comment by Notsfsssf** [comment]
墙内这个ReCAPTCHA是有问题的，但是没有挂代理或者试错密码太多次是不会出的，如果有代理，避免使用公交车代理，使用chrome登录，也能正确通过验证
