### ISSUE TITLE
动图下载后只有单张jpg

### ISSUE THREAD

**Issue by DogTorrent** [Notsfsssf/pixez-flutter#278]
ugoira可以播放，但是详情页面无法下载，在列表可以长按下载但是下载出来只有单张jpg

比如：[88242257](https://www.pixiv.net/artworks/88242257)这张

可以考虑在下载时将ugoira转为webm？

**Comment by Notsfsssf** [comment]
长按可以合成成gif
我试过合成anim webp，能实现，包会大一点，但是最关键的是，没有主流的im是支持动态webp的
要么是转换成gif要么干脆不能动或者不支持，目前就见过WhatsApp支持，telegram不支持要转，qq也是要转，不太现实
webm的话，主流IM有明确的支持场景么，，可以考虑当附加包增加进去

**Comment by DogTorrent** [comment]
> 长按可以合成成gif
> 我试过合成anim webp，能实现，包会大一点，但是最关键的是，没有主流的im是支持动态webp的
> 要么是转换成gif要么干脆不能动或者不支持，目前就见过WhatsApp支持，telegram不支持要转，qq也是要转，不太现实
> webm的话，主流IM有明确的支持场景么，，可以考虑当附加包增加进去

😂居然没发现这个功能...
不过webm的话，确实没啥im支持，tg不发原图应该是转成mp4吧？其实我只是觉得webm会比gif质量高一点，体积小一点。（~~其实最主要还是因为网上找到在线服务（比如[这种](http://ugoira.dataprocessingclub.org/)）提供的是ugoira转webm~~）

anim webp的话，如果能做那应该比gif好，理论上比起webm也方便一些（指不需要播放器），但是我试了下，webp（apng也是）无论是在手机的图库里查看还是tg发送后都是静态图，支持成谜......

话说回来，pixiv官方客户端是怎么处理ugoira的啊...不会真的把图片序列打包成zip吧

**Comment by Notsfsssf** [comment]
> > 长按可以合成成gif
> > 我试过合成anim webp，能实现，包会大一点，但是最关键的是，没有主流的im是支持动态webp的
> > 要么是转换成gif要么干脆不能动或者不支持，目前就见过WhatsApp支持，telegram不支持要转，qq也是要转，不太现实
> > webm的话，主流IM有明确的支持场景么，，可以考虑当附加包增加进去
> 
> 😂居然没发现这个功能... 不过webm的话，确实没啥im支持，tg不发原图应该是转成mp4吧？其实我只是觉得webm会比gif质量高一点，体积小一点。（~其实最主要还是因为网上找到在线服务（比如[这种](http://ugoira.dataprocessingclub.org/)）提供的是ugoira转webm~）
> 
> anim webp的话，如果能做那应该比gif好，理论上比起webm也方便一些（指不需要播放器），但是我试了下，webp（apng也是）无论是在手机的图库里查看还是tg发送后都是静态图，支持成谜......
> 
> 话说回来，pixiv官方客户端是怎么处理ugoira的啊...不会真的把图片序列打包成zip吧（刚刚乱翻翻到了[这个](https://github.com/pixiv/zip_player)）

官方就是把画师投稿的动图存成zip的，然后播放的时候拆出来，用canvas现场画，合成webm倒是可以研究一下。
