### ISSUE TITLE
无法用鼠标上下滑动

### ISSUE THREAD

**Issue by Miuzarte** [Notsfsssf/pixez-flutter#280]
滚轮能用  但是幅度很小（不知道是不是MIUI的锅）
看图界面鼠标可以左右滑动切换上一张下一张
任何界面都不能鼠标按住上下拖拽来滑动

**Comment by nothingshiru** [comment]
EMUI也是一样滚动幅度小。
我记得PixEZ之前是支持按住鼠标左键并上下拖拽来滑动页面的，现在不行了。
EMUI升级鸿蒙后，在某些使用场景中滚动鼠标滚轮是模拟按住鼠标左键并上下拖拽的操作，现在因为PixEZ不支持按住鼠标左键并上下拖拽来滑动页面的操作，导致滚轮也完全无法使用了。

**Comment by Notsfsssf** [comment]
这个需要联调解决，我并没有对应的设备，可以添加一下telegram的群组帮忙测试一下 @Miuzarte  @nothingshiru

**Comment by nothingshiru** [comment]
> 这个需要联调解决，我并没有对应的设备，可以添加一下telegram的群组帮忙测试一下

我看到有2个群，一个人多的一个人少的，请问我该加哪个群？
