### ISSUE TITLE
登录不上ERR_EMPTY_RESPONS

### ISSUE THREAD

**Issue by qoolxh** [Notsfsssf/pixez-flutter#285]
登录不上ERR_EMPTY_RESPONSE
先是出现the certificate authority is not trusted,continue?
本来能用，但是想着开代理上p站结果忘了密码给退登录了，再登录就出现错误，是最新版本下载包32m那个。

**Comment by Notsfsssf** [comment]
你可以右上角用chrome登录，只要代理没问题

**Comment by qoolxh** [comment]
> 你可以右上角用chrome登录，只要代理没问题

不用代理直接上还是不行。用手机app没有chrome。用代理上软件也上不了。但是直接登p站可以
