### ISSUE TITLE
小米6手机上无法赋予文件访问权限

### ISSUE THREAD

**Issue by non1996** [Notsfsssf/pixez-flutter#29]
应用权限管理中没有类似“文件”的选项。“读写手机存储”设置中也找不到pixex程序

**Comment by Aitosumi** [comment]
小米10也有一样的问题

**Comment by Aitosumi** [comment]
> 小米10也有一样的问题

已经找到解决方案了
https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E4%B8%8B%E8%BD%BD%E5%9B%BE%E7%89%87
