### ISSUE TITLE
ios保存图片会被压缩

### ISSUE THREAD

**Issue by Sliverala** [Notsfsssf/pixez-flutter#292]
如题
下载图片发现通过app下载的图片比通过pixiv网页下载的小很多
抓包看到app请求返回图片大小和通过网页保存的是一致的（app下载的只有1.5m，网页保存和这里返回的都是4.9m）
![0B3C28FA-7F89-4FA1-A59B-9EAB8A687806](https://user-images.githubusercontent.com/20553512/144715635-084de734-389e-4a17-8662-c5a5cb37517e.jpeg)
应该是保存到相册被ios压缩了，不知道有没有办法可以保存原图

OS：ios 1.5.1.1
app版本：1.6.8

**Comment by Notsfsssf** [comment]
给个测试插画id呗。。很明显能判断到大小被压缩的测试id，我方便测试
应该是保存到相册被ios压缩了

**Comment by Sliverala** [comment]
> 给个测试插画id呗。。很明显能判断到大小被压缩的测试id，我方便测试
> 应该是保存到相册被ios压缩了

94232556
保存后大小从7.2到2.5，dpi 从96变为72

**Comment by Notsfsssf** [comment]
> > 给个测试插画id呗。。很明显能判断到大小被压缩的测试id，我方便测试
> > 应该是保存到相册被ios压缩了
> 
> 94232556 保存后大小从7.2到2.5，dpi 从96变为72

定位到问题了，我需要重新写一下这个保存到相册的逻辑，可能更新会慢一些了

**Comment by Sliverala** [comment]
> 

非常感谢

另，试了一下官方app，发现也有一模一样的问题😂

**Comment by Notsfsssf** [comment]
已解决
