### ISSUE TITLE
LineageOS 17.1 基于红米9A，点击图片查看原图会出现这样的情况。

### ISSUE THREAD

**Issue by tense11** [Notsfsssf/pixez-flutter#294]
![Screenshot_20211206-220023_PixEz](https://user-images.githubusercontent.com/37732785/144859597-c236d211-ed63-425a-8b63-bd678349f58a.png)

**Comment by tense11** [comment]
最新的0.7.0 版本，release下载的

**Comment by PYUDNG** [comment]
+1
