### ISSUE TITLE
［功能建议］隐私屏幕

### ISSUE THREAD

**Issue by sertwen** [Notsfsssf/pixez-flutter#303]
![Screenshot_202112290114](https://user-images.githubusercontent.com/56821010/147593692-8d2cd53f-2742-45a4-8723-2168a1083554.png)
谨防社死

**Comment by PYUDNG** [comment]
+001.0

**Comment by Notsfsssf** [comment]
目前Android端并不能实现“在最近任务界面遮罩，应用在前台时允许截图”的功能   
我觉得应当是由系统来定制一个生物识别锁之类的

**Comment by sertwen** [comment]
> 目前Android端并不能“在任务界面显示罩，应用在前台时允许实现截图”的功能 我觉得应该是由系统来定制一个生物识别锁之类的

其实这是我开Xposed插件截的图啦，只是希望后台卡片能隐藏内容就好（比如正在浏览R18），就像这样

https://user-images.githubusercontent.com/56821010/151814130-b7bdb752-46e7-4804-8956-15929187fab2.mp4
