### ISSUE TITLE
Share to open

### ISSUE THREAD

**Issue by takase1121** [Notsfsssf/pixez-flutter#311]
Now, I usually open links from YouTube. YouTube puts its own redirect on the links so it wouldn't get picked up by Android. It'll be better if I could "share to" pixez from the browser. It's possible to open links from the search bar so I don't see why it'll be impossible to allow sharing.

**Comment by Notsfsssf** [comment]
Android12？you can try to enable open by default
![photo_2022-01-30_22-04-04](https://user-images.githubusercontent.com/16934707/151702997-400059d1-cd17-445d-bb60-141bb7bf8b64.jpg)
t

**Comment by takase1121** [comment]
Android 12 is an incredibly high bar. I'm referring to this kind of menu (when you click share in chromium).
![image](https://user-images.githubusercontent.com/20792268/151705838-d1629075-00ce-4e13-a620-580638cd6513.png)

Since pixez already allows sharing images for saucenao, why isn't URL supported?

**Comment by Notsfsssf** [comment]
Supported

**Comment by takase1121** [comment]
Sorry, but the feature didn't work as intended:

Currently:

https://user-images.githubusercontent.com/20792268/156907274-419e1392-f99a-401e-b0e5-944b02b72833.mp4

Intended (may be NSFW?):
<details>

https://user-images.githubusercontent.com/20792268/156907280-351eb230-8a2f-4ef3-8845-15b1bee80706.mp4
</details>
