### ISSUE TITLE
dio使用http2进行连接

### ISSUE THREAD

**Issue by VoidxHoshi** [Notsfsssf/pixez-flutter#313]
http2对画廊式网站应该提升很大，
使用该插件https://github.com/flutterchina/dio/tree/master/plugins/http2_adapter

**Comment by Notsfsssf** [comment]
是指图床还是api?

**Comment by Notsfsssf** [comment]
已测试，服务器不支持

**Comment by yfdyh000** [comment]
> 已测试，服务器不支持

是哪个服务器不支持。Http2 test工具显示都可以。

**Comment by Notsfsssf** [comment]
> > 已测试，服务器不支持
> 
> 是哪个服务器不支持。Http2 test工具显示都可以。

我试过用dio HTTP2进行api服务器的连接，返回了错误信息
有可能是直连配置问题，有可能他就是不支持，我实在不想在这种没有经过完整实验的情况下去试了，如果你能用代码举出完整的用例再开一个issue吧
