### ISSUE TITLE
[功能建议]标签筛选

### ISSUE THREAD

**Issue by Xcxglily** [Notsfsssf/pixez-flutter#315]
我提个小小的建议哦，收藏图片的时候都是直接点❤️，图片默认是“未分类”，后续想在已收藏的几千张图片里找出带有指定标签的图很麻烦，

所以希望可以出一个只搜出已收藏的图片的功能，或者说在筛选功能再加一个选择
![无标题100](https://user-images.githubusercontent.com/99279590/153044300-9ff49018-c0e0-461f-88aa-30a2cc6be8ef.jpg)

**Comment by Notsfsssf** [comment]
这个我也想做，但是服务端的接口不支持这个特性，所以没辙
