### ISSUE TITLE
iOS 端希望加入系統的日文語言選項

### ISSUE THREAD

**Issue by TragicLifeHu** [Notsfsssf/pixez-flutter#319]
雖然本軟體的語言切換不受 iOS 設定中那個語言選項影響
但在 iOS 裝置上，分享/儲存等會用到系統介面的部分會受到那個設定的影響
在我拿到 iOS 日文機器後就發現「分享圖片」頁面對應的系統選項只能使用英文/中文

希望這一個簡單細節能夠被改善

以此類推，其他受支援語言也可以加入

**Comment by Notsfsssf** [comment]
已更新
