### ISSUE TITLE
华为荣耀v30 PRO无法保存图片闪退，无法选择储存文件目录

### ISSUE THREAD

**Issue by shurac31** [Notsfsssf/pixez-flutter#32]
Android版本：10
问题如图

![QQ图片20200925090917](https://user-images.githubusercontent.com/71858210/94215337-e6801480-ff0e-11ea-8997-dfd40f9aee5f.jpg)
![QQ图片20200925090924](https://user-images.githubusercontent.com/71858210/94215340-e8e26e80-ff0e-11ea-964c-f8b409614de1.jpg)
![QQ图片20200925090926](https://user-images.githubusercontent.com/71858210/94215341-e97b0500-ff0e-11ea-9418-ccbdd38babab.jpg)

**Comment by shurac31** [comment]
求dalao解决，谢谢！

**Comment by Romani-Archman** [comment]
请查阅[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md)
