### ISSUE TITLE
[BUG] 在 Android 12 上與手勢操作衝突

### ISSUE THREAD

**Issue by TragicLifeHu** [Notsfsssf/pixez-flutter#328]
在 Android 12 中使用 PixEz 時，如果使用手勢操作 (小橫條/白條)，其中一個滑動顯示最近工作 (Resent Task) 的操作將極其難以觸發
快速上划回到桌面的手勢也會造成畫面 glitch
滑動邊緣返回 仍正常使用

**Comment by Notsfsssf** [comment]
我在Android virtual emulator上没有复现出来，我询问了一些group里使用类原生android12系统(dot,pe)的用户，没有发现问题，具体的现象能提供一下动图么

**Comment by TragicLifeHu** [comment]
經過測試是4K螢幕下，4K的 PixEz 和2K桌面自動切換造成的問題，強制2K執行後問題消失了
