### ISSUE TITLE
无法批量保存的问题

### ISSUE THREAD

**Issue by MsLingYue** [Notsfsssf/pixez-flutter#34]
长按使用单张图片保存正常，但是在详情页右上角使用多选保存的话无法保存图片，而且下载页面里也看不到任务。
另外就是能像以前一样加回下载按钮吗，现在下载好麻烦，列表界面以前收藏旁边有个下载按钮现在改成了长按，多图的详情页面一张张下载好麻烦诶，多选的话也要一张张打勾，mate20现在多选保存功能又保存不了图片。

**Comment by Notsfsssf** [comment]
已修复
