### ISSUE TITLE
saf模式无法正确授权

### ISSUE THREAD

**Issue by waaaaagh** [Notsfsssf/pixez-flutter#35]
进入出现选择目录弹框的时候,点击开始会出现"未正确取得授权,可能会导致部分功能失效或闪退"

机型:小米mix2
android版本9
处理器骁龙835

**Comment by akihibi-yamane** [comment]
同问题，选择目录时默认目录为download，无法选为下载目录，且无法新建文件夹
机型小米k30
Android版本10
骁龙765g

**Comment by Romani-Archman** [comment]
download不能作为目录,查阅[FAQ}(https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md)

**Comment by UpKiry** [comment]
小米手机只能选download目录 没办法 哎
小米CC9e
Android 10

**Comment by Notsfsssf** [comment]
麻烦查阅一下[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E9%80%89%E6%8B%A9%E5%82%A8%E5%AD%98%E7%9B%AE%E5%BD%95)这些操作都是挺简单的，只要肯去思考

**Comment by UpKiry** [comment]
> 麻烦查阅一下[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E9%80%89%E6%8B%A9%E5%82%A8%E5%AD%98%E7%9B%AE%E5%BD%95)这些操作都是挺简单的，只要肯去思考

这其实应该是小米MIUI的问题

**Comment by Notsfsssf** [comment]
> > 麻烦查阅一下[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E9%80%89%E6%8B%A9%E5%82%A8%E5%AD%98%E7%9B%AE%E5%BD%95)这些操作都是挺简单的，只要肯去思考
> 
> 这其实应该是小米MIUI的问题

不是，你可以先看一下FAQ里提到的怎么选目录，那我复制过来好了，你既然能看到download目录，说明SAF是可行的，没有被系统禁用
点击右上角的三个点，选择「显示内部存储空间 (Show internal storage)」（如果是「隐藏内部存储空间(Hide internal Storage)」则无需再点选
打开左侧栏，找到你的手机内部存储空间（一般为手机图标 + 手机型号，可用空间 XX GB）
找到 Pictures 目录，如果你还没有 PixEz 目录则从右上角的三个点中选择「新建文件夹」 进入刚建立的 PixEz 目录，点击下面的「选择」

**Comment by UpKiry** [comment]
可用 打扰到您了 抱歉
