### ISSUE TITLE
发表评论时有显示问题

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#371]
如果评论区已经有一个评论`A: 123`

这时候我发一个评论 `456`

就会显示成 `我: 123`

只有退出评论再重新打开才能正确显示：

```
我: 456
A: 123
```

**Comment by EmptyDreams** [comment]
该问题目前仍然存在，并且评论发布时间也有问题，我是九点多发送的评论却显示一点多。

![发布](https://user-images.githubusercontent.com/44894906/204115429-3a1438c1-c458-4e05-a914-55693e81e95d.png)

![重进](https://user-images.githubusercontent.com/44894906/204115432-b2eba81f-36c0-4157-a423-af5fabca3a11.png)

第一张图是我发布评论后，第二张图是我退出评论页面重进后。

**Comment by Notsfsssf** [comment]
第一个确实有问题
第二个是yyyy-MM-dd HH:mm格式现实的，+0时区不是+8,之前显示的是带T时区的时间戳，但是那样比较长
