### ISSUE TITLE
添加小说到插画的链接跳转

### ISSUE THREAD

**Issue by SherkeyXD** [Notsfsssf/pixez-flutter#395]
如图情况![IMG_20220815_215011.jpg](https://user-images.githubusercontent.com/57581480/184647935-99e71b05-6e56-4dd3-828d-114f4a7cbe02.jpg)
能否实现点击后应用内跳转，或者更进一步直接显示在小说内呢？

**Comment by Notsfsssf** [comment]
给一下这个小说的id吧，我试试

**Comment by SherkeyXD** [comment]
> 给一下这个小说的id吧，我试试

小说id为18110574，文章开头西面一点点就有图片
先行感谢

**Comment by Notsfsssf** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/16934707/185668896-0212bea8-ce92-4985-b970-c0165ae55077.png">
我注意到这个链接返回的就是指向网页的id，n开头的链接，所以我并不能正确解析到封面的详情，看来移动端只有通过网页才能看到封面

**Comment by Notsfsssf** [comment]
作者可能是使用了通过上传添加插画而不是id，拿不到id就无法解析出图片的url，没有办法了
<img width="174" alt="image" src="https://user-images.githubusercontent.com/16934707/185669349-6da625d8-b879-4c25-92aa-c911dcd4cc02.png">

**Comment by SherkeyXD** [comment]
我大概懂了，应该类似github中issue上传的图片和直接保存在git仓库中图片的区别
那应该是没有办法了

**Comment by SherkeyXD** [comment]
> 我大概懂了，应该类似github中issue上传的图片和直接保存在git仓库中图片的区别
> 那应该是没有办法了
> 

能否使用与封面图片类似的方法来渲染文章内图片呢

**Comment by Notsfsssf** [comment]
> > 我大概懂了，应该类似github中issue上传的图片和直接保存在git仓库中图片的区别
> > 那应该是没有办法了
> 
> 能否使用与封面图片类似的方法来渲染文章内图片呢

这个作品里有两个以上个插图，但是每个插图api返回的信息都是[[jumpxxx,链接都是一样的，可见是只有web端有提供数据了

**Comment by Notsfsssf** [comment]
我使用了官方客户端，官方客户端能正常展示出来，那应该是接口升级了，我试试看能不能拿到新接口就能解决

**Comment by SherkeyXD** [comment]
看来是无法实现，那我关issue了

**Comment by Notsfsssf** [comment]
![image](https://user-images.githubusercontent.com/16934707/186661437-8818fd56-6bd8-416e-bb4a-16344fedc017.png)
抓取请求后发现,p站已经开始用webview展示小说了，移动端基本上是没辙了

**Comment by SherkeyXD** [comment]
看来是不行了，那我关issue
