### ISSUE TITLE
程序出错，即将退出

### ISSUE THREAD

**Issue by CENTURYWIND** [Notsfsssf/pixez-flutter#403]
程序出错，即将退出
Not inplemented

更新最新版本后就这样了

**Comment by Notsfsssf** [comment]
系统版本有无

**Comment by CENTURYWIND** [comment]
> 系统版本有无

Android 11，安全更新2022.02.05
Color OS V11

**Comment by Notsfsssf** [comment]
> > 系统版本有无
> 
> Android 11，安全更新2022.02.05 Color OS V11

重下有没有办法解决，有没有完整的错误日志，下最大的那个apk

**Comment by CENTURYWIND** [comment]
> > > 系统版本有无
> > 
> > 
> > Android 11，安全更新2022.02.05 Color OS V11
> 
> 重下有没有办法解决，有没有完整的错误日志，下最大的那个apk

重下最大的那个包已经试过了，没用，还是这样
错误日志的话没有，因为一启动就以文字框的形式提示问题内容

**Comment by CENTURYWIND** [comment]
![Uploading Screenshot_2022-08-30-19-18-47-33_d0227c5c1fdea5294b7ca62b7e394096.jpg…]()

**Comment by CENTURYWIND** [comment]
![Screenshot_2022-08-30-19-18-47-33_d0227c5c1fdea5294b7ca62b7e394096](https://user-images.githubusercontent.com/42110470/187424025-214148b1-7740-47bb-a6d9-60da133e3b7c.jpg)

**Comment by Notsfsssf** [comment]
[app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454013/app-arm64-v8a-release.apk.zip)
要是有详细的日志就好了，这里打包了一个可能打印出详细堆栈的包

**Comment by CENTURYWIND** [comment]
> [app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454013/app-arm64-v8a-release.apk.zip) 要是有详细的日志就好了，这里打包了一个可能打印出详细堆栈的包
![Screenshot_2022-08-30-23-21-31-50_d0227c5c1fdea5294b7ca62b7e394096](https://user-images.githubusercontent.com/42110470/187476677-ec6c9628-575b-459e-a3d7-57d631dcb97f.jpg)

[Ljava.lang. StackTraceElement;@18241ee

这次确实有堆栈了

**Comment by Notsfsssf** [comment]
[app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454240/app-arm64-v8a-release.apk.zip)

**Comment by CENTURYWIND** [comment]
> [app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454240/app-arm64-v8a-release.apk.zip)

java.lang.llegalStateException: Not

implemented

at

androidx.work.CoroutineWorkerv(Unknow

n Source:4)

at

androidx.work.CoroutineWorker.u(Unknow

n Source:0)

at

androidx.work.CoroutineWorker$b.x(Unkn

own Source:38)

at e9.a.j(Unknown Source:11)

at kotlinx.coroutines.b1.run(Unknown

Source:88)

at

kotlinx.coroutines.scheduling.a.K(Unknow

n Source:0)

at

kotlinx.coroutines.scheduling.a$c.d(Unkno

wn Source:14)

at

kotlinx.coroutines.scheduling.a$c.n(Unkno

wn Source:28)

at

kotlinx.coroutines.scheduling.a$c.run(Unk

nown Source:0)

Suppressed: kotlinx.coroutines.z0:[t2íCancelling!@89aa69b,

Dispatchers.Default]
![Screenshot_2022-08-30-23-34-35-65_d0227c5c1fdea5294b7ca62b7e394096](https://user-images.githubusercontent.com/42110470/187479876-1b90efa8-38ab-4def-85dd-00c36219da83.jpg)

**Comment by Notsfsssf** [comment]
[app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454533/app-arm64-v8a-release.apk.zip)
应该能解决问题

**Comment by CENTURYWIND** [comment]
> [app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454533/app-arm64-v8a-release.apk.zip) 应该能解决问题

java.lang.llegalArgumentException:Invalid notification (no valid smallicon): Notification(channel=AppWidgetshortcut=null contentView =nullvibrate=null sound=null defaults=0x0flags=0x0 color=0x00000000

vis=PRIVATE)

at

android.app.NotificationManagerfixNotification(NotificationManager.java:603)

at

android.app.NotificationManager.notifyAsUser(NotificationManager.java:582)

at

android.app.NotificationManager.notify(

otificationManager.java:531)

at

android.app.NotificationManager.notify(

otificationManagerjava:507)

at

androidx.work.impl.foreground.SystemForegroundService$b.run(Unknown

Source:8)

at
 android.os.Handler.handleCallback(Handltabvd

er.java:938)

at

android.os.Handler.dispatchMessage(Han

dlerjava:99)

at

android.os.Looper.loop(Looper.java:257)

at

android.app.ActivityThread.main(Activity

hread.java:8307)

at java.lang.reflect.Method.invoke(Native

Method)

at
![Screenshot_2022-08-31-00-05-15-97_d0227c5c1fdea5294b7ca62b7e394096](https://user-images.githubusercontent.com/42110470/187486801-3d04ea50-dc42-4a99-a96e-95c49fd0f2a1.jpg)
并不行……

**Comment by Notsfsssf** [comment]
[app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454898/app-arm64-v8a-release.apk.zip)
新问题...

**Comment by CENTURYWIND** [comment]
> [app-arm64-v8a-release.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9454898/app-arm64-v8a-release.apk.zip) 新问题...

Ok，这次没有报错了，大概试了试没发现什么问题
辛苦了
