### ISSUE TITLE
安卓微件加载不出图片

### ISSUE THREAD

**Issue by 1gugugu** [Notsfsssf/pixez-flutter#409]
一加七手机（1+7）
安卓系统11
![Screenshot_20220903-192434__01](https://user-images.githubusercontent.com/112758708/188268264-d4edf4cc-d3ab-46ba-92d1-1fcfd771b55d.jpg)
![Screenshot_20220903-192440__01](https://user-images.githubusercontent.com/112758708/188268266-7daad19d-a7de-4ead-84bb-c2a481b26231.jpg)
安卓微件
一直转圈显示英文
Please view
...    .    .

图片pixez任务栏提示
隔一会弹一个提示
Fetching
Fetching widget illust

**Comment by Notsfsssf** [comment]
设置内可以调整推荐的种类，可能是没有拉到数据

**Comment by PYUDNG** [comment]
设置哪里可以调整推荐种类？
![Screenshot_20220905_022707_edit_1189729291214815](https://user-images.githubusercontent.com/63054558/188328446-a81b3ce9-cc03-41b9-ba5d-b06debddc094.jpg)
![Screenshot_20220905_022712_com perol pixez_edit_1189657148998680](https://user-images.githubusercontent.com/63054558/188328451-15dd03ff-2fab-445d-a7b4-21aca30fd590.jpg)
![Screenshot_20220905_022845_edit_1189906145553850](https://user-images.githubusercontent.com/63054558/188328453-fdb10b45-aaf7-434c-957f-c6a20cd45b5a.jpg)

也是有这个问题，不过光是加载不出来，通知栏没有通知
![Uploading Screenshot_20220905_023616_com.huawei.android.launcher_edit_1190313520268371.jpg…]()

**Comment by PYUDNG** [comment]
也是有这个问题，不过光是加载不出来，通知栏没有通知
![Screenshot_20220905_023616_com huawei android launcher_edit_1190313520268371](https://user-images.githubusercontent.com/63054558/188328698-67bec6f9-8081-4c46-b043-06c044ca87f7.jpg)

**Comment by wf1594149160** [comment]
最新版桌面小组件需要挂梯子才能使用，不挂就这样了，软件内的代理好像对桌面小组件不起作用

**Comment by 1gugugu** [comment]
> 最新版桌面小组件需要挂梯子才能使用，不挂就这样了，软件内的代理好像对桌面小组件不起作用

好的
