### ISSUE TITLE
支持高刷吗？

### ISSUE THREAD

**Issue by beishuangzz** [Notsfsssf/pixez-flutter#41]
本人手机一加8，不能高刷，似乎只有60hz

**Comment by Notsfsssf** [comment]
在设置页右上角点进去，显示模式，可以选择显示模式锁定高刷

**Comment by beishuangzz** [comment]
> 在设置页右上角点进去，显示模式，可以选择显示模式锁定高刷

谢谢，没注意到还有这个设置
