### ISSUE TITLE
请问iOS版本下架了，未来还有可能重新上线吗？谢谢

### ISSUE THREAD

**Issue by iPixelOldC** [Notsfsssf/pixez-flutter#411]
今天恰好看到又有新的版本更新了，才想起我手机上APP好久没更新，登美区号一看，原来是下架了。这未来还有重新上线的希望嘛？O(∩_∩)O 谢谢

**Comment by Notsfsssf** [comment]
非国区非日区应该还有，需要卸载了装

**Comment by iPixelOldC** [comment]
> 非国区非日区应该还有，需要卸载了装

谢谢。懂了，原来这软件我是拿国区大号下载的。现在我用美区用的多，直接给忘了。ᶘ ᵒᴥᵒᶅ
