### ISSUE TITLE
Trying to copy the tag from searchbar crashes app.

### ISSUE THREAD

**Issue by kyoyacchi** [Notsfsssf/pixez-flutter#414]
https://user-images.githubusercontent.com/63583961/190845805-3e451879-2fd9-4951-8c66-7119ade448ed.mp4

Here it is.
It crashed when i click "Copy"(Kopyala)

Same for other tags.

**Comment by Notsfsssf** [comment]
seems like https://github.com/flutter/flutter/issues/110640
I will fix it in next version
[app-arm64-v8a-release 2.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9594397/app-arm64-v8a-release.2.apk.zip)

**Comment by kyoyacchi** [comment]
> seems like [flutter/flutter#110640](https://github.com/flutter/flutter/issues/110640) I will fix it in next version [app-arm64-v8a-release 2.apk.zip](https://github.com/Notsfsssf/pixez-flutter/files/9594397/app-arm64-v8a-release.2.apk.zip)

Still same
