### ISSUE TITLE
调整显示高刷新率后没有效果

### ISSUE THREAD

**Issue by xperiazu21** [Notsfsssf/pixez-flutter#415]
手机是谷歌Pixel 6
系统Android 13

在版本0.9.4时，不需调整就有90Hz显示
更新到0.9.5后，就变成60Hz了
强制设90Hz，用开发者选项看屏幕是90Hz显示，但是应用内还是只有60Hz
0.9.6版本也是一样情况

**Comment by Notsfsssf** [comment]
可能是flutter sdk升级的锅，我找找有没有相关解决办法

**Comment by xperiazu21** [comment]
更新0.9.8版本后，经测试已可正常使用高刷新率，谢谢修复！
