### ISSUE TITLE
图床问题 以及暂时的解决方案

### ISSUE THREAD

**Issue by PYUDNG** [Notsfsssf/pixez-flutter#427]
图床问题是今天或者昨天才出现的。i.pixiv.re（cat站反代）返回空response导致不能载图，如果用原始的i.pximg.net则又慢还频繁无法访问。

**Comment by PYUDNG** [comment]
一个下午写了个适用于heroku的pixiv图床反代：[pixiv-reverse](https://github.com/PYUDNG/pixiv-reverse)，已经跑通（边学边写代码乱得一匹
由于用的是free heroku账号每月资源有限（还得跑其他项目），app地址就不分享了，自己去heroku注册帐号部署一下就能用

**Comment by yfdyh000** [comment]
> 一个下午写了个适用于heroku的pixiv图床反代：[pixiv-reverse](https://github.com/PYUDNG/pixiv-reverse)，已经跑通（边学边写代码乱得一匹 由于用的是free heroku账号每月资源有限（还得跑其他项目），app地址就不分享了，自己去heroku注册帐号部署一下就能用

免费heroku，今年11月28日终止服务。

**Comment by PYUDNG** [comment]
> heroku

啊这…是这样的吗
我都没注意到

**Comment by yfdyh000** [comment]
如果是"返回空response"，参考 https://github.com/xuejianxianzun/PixivBatchDownloader/issues?q=%E7%A9%BA%E6%95%B0%E6%8D%AE+is%3Aclosed ，可能P站限制了图床IP的访问频次。

**Comment by PYUDNG** [comment]
> 如果是"返回空response"，参考 https://github.com/xuejianxianzun/PixivBatchDownloader/issues?q=%E7%A9%BA%E6%95%B0%E6%8D%AE+is%3Aclosed ，可能P站限制了图床IP的访问频次。

要真是这个原因…恐怕以后都得自行部署了…
但我记得P站限速好像已经有一些日子了，为啥这两天反代才开始出问题（

**Comment by 1235689hhh** [comment]
今天p站更新了最新的图片阅读器，估计是这个搞出的问题，图床是i.pximg.net

**Comment by liuxinyu970226** [comment]
要不谁能召唤一下cat那个站长？

**Comment by PYUDNG** [comment]
bad news guys，代码是周五写的，app是周六上线的，herokuapp的域名是周一墙的
我刚搭的app啊

**Comment by PYUDNG** [comment]
网页端始终可以纯Nginx域前置访问pixiv本站和i.pximg.net图床，不知道APP是否可以做到。
https://github.com/Notsfsssf/pixez-flutter/issues/431

**Comment by PYUDNG** [comment]
herokuapp的域名又通了（😅
