### ISSUE TITLE
SNI Bypass 是否覆盖了pixiv原始图床？

### ISSUE THREAD

**Issue by PYUDNG** [Notsfsssf/pixez-flutter#431]
PC网页端纯本地Nginx域前置是可以正常稳定访问i.pximg.net的
app里开启绕过SNI嗅探时、图床为i.pximg.net时却无法加载图片
请问是否有机会直连i.pximg.net呢？

谢谢。

**Comment by Notsfsssf** [comment]
那个开关打开是把所有副作用全部去掉的，完全不做任何处理
关闭的状态下是启用了直连，连接图床会启用硬编码的域名前置
但是国内没有一家dns没有被污染支持dnsoverhttps，所以采用硬编码的方式，
可能是硬编码的ip有了问题

**Comment by PYUDNG** [comment]
如果可以的话希望可以自定义host和dnsoverhttps的服务器地址；这个历史issue先close了。
