### ISSUE TITLE
使用软件的过程中出现边框

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#437]
这个问题我曾经提交过 issuse https://github.com/Notsfsssf/pixez-flutter/issues/329

在 0.9.8 版本再次遇到同样问题。

这个边框在切换到其它应用再切换回来就会消失。

**Comment by Notsfsssf** [comment]
我觉得是flutter sdk stable又改了啥，我搜到的issues有提到过这类问题https://github.com/flutter/flutter/issues/16810
解决方案是把高亮显示焦点设为false，但是这好像会影响平板键鼠之类的问题
我可以把这个先加到下一版，看看用户反馈
