### ISSUE TITLE
mi10无法保存图片，保存图片会闪退，无法找到保存地址

### ISSUE THREAD

**Issue by Bailin7** [Notsfsssf/pixez-flutter#44]

**Comment by Notsfsssf** [comment]
更新到最新版，修改保存目录

**Comment by porSilent** [comment]
我也是MIUI系统，小米8se，MIUI 11.0.3稳定版，已经更新到2.2l，已经给了读写存储权限
![Screenshot_2020-10-11-00-25-13-223_com miui securitycenter](https://user-images.githubusercontent.com/72664255/95660114-40601b80-0b58-11eb-8336-72078682ba48.jpg)
但是在选择保存文件夹的时候无法读取选择文件夹，在虚拟sd卡根目录下都看不到文件夹
![Screenshot_2020-10-11-00-23-32-072_com perol pixez](https://user-images.githubusercontent.com/72664255/95660073-055de800-0b58-11eb-9768-20258be802f0.jpg)
saf模式下选择文件夹也是空白的看不到文件夹
![Screenshot_2020-10-11-00-30-10-672_com google android documentsui](https://user-images.githubusercontent.com/72664255/95660239-0a6f6700-0b59-11eb-9630-5f00b90dfea8.jpg)
开始下载任务就会提示出错并闪退
![Screenshot_2020-10-11-00-29-17-553_com perol pixez](https://user-images.githubusercontent.com/72664255/95660206-dac05f00-0b58-11eb-83c7-074c0d03c69f.jpg)

**Comment by porSilent** [comment]
同样调用saf的chrome就没有这个问题，我怀疑是不是默认参数不合适。回头我用老一点的MIUI版本试一下，saf的默认参数应该不会影响内存读写权限的使用啊

**Comment by Notsfsssf** [comment]
> 同样调用saf的chrome就没有这个问题，我怀疑是不是默认参数不合适。回头我用老一点的MIUI版本试一下，saf的默认参数应该不会影响内存读写权限的使用啊

如果你不会看[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E9%80%89%E6%8B%A9%E5%82%A8%E5%AD%98%E7%9B%AE%E5%BD%95)的话，我帮你复制过来
回到正题，我们推荐选择的路径是 Pictures/PixEz ，当然一般来说这个路径不会从一开始就存在，所以往往文件夹需要自己来创建。

具体一点的操作方式如下：

点击右上角的三个点，选择「显示内部存储空间 (Show internal storage)」（如果是「隐藏内部存储空间(Hide internal Storage)」则无需再点选
打开左侧栏，找到你的手机内部存储空间（一般为手机图标 + 手机型号，可用空间 XX GB）
找到 Pictures 目录，如果你还没有 PixEz 目录则从右上角的三个点中选择「新建文件夹」 进入刚建立的 PixEz 目录，点击下面的「选择」
注意，保存路径不能包含 Download (下载)目录，所以最好选择 Pictures/PixEz 路径。

**Comment by Bailin7** [comment]
解决了，感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Perol_Notsfsssf&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月11日(星期天) 上午9:45
收件人:&nbsp;&quot;Notsfsssf/pixez-flutter&quot;<pixez-flutter@noreply.github.com&gt;;
抄送:&nbsp;&quot;Bailin7&quot;<964658136@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Notsfsssf/pixez-flutter] mi10无法保存图片，保存图片会闪退，无法找到保存地址 (#44)

**Comment by porSilent** [comment]
> > 同样调用saf的chrome就没有这个问题，我怀疑是不是默认参数不合适。回头我用老一点的MIUI版本试一下，saf的默认参数应该不会影响内存读写权限的使用啊
> 
> 如果你不会看[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E9%80%89%E6%8B%A9%E5%82%A8%E5%AD%98%E7%9B%AE%E5%BD%95)的话，我帮你复制过来
> 回到正题，我们推荐选择的路径是 Pictures/PixEz ，当然一般来说这个路径不会从一开始就存在，所以往往文件夹需要自己来创建。
> 
> 具体一点的操作方式如下：
> 
> 点击右上角的三个点，选择「显示内部存储空间 (Show internal storage)」（如果是「隐藏内部存储空间(Hide internal Storage)」则无需再点选
> 打开左侧栏，找到你的手机内部存储空间（一般为手机图标 + 手机型号，可用空间 XX GB）
> 找到 Pictures 目录，如果你还没有 PixEz 目录则从右上角的三个点中选择「新建文件夹」 进入刚建立的 PixEz 目录，点击下面的「选择」
> 注意，保存路径不能包含 Download (下载)目录，所以最好选择 Pictures/PixEz 路径。

不是，我是说传统模式，我是说传统模式在获得读写存储权限以后依然不能读取文件目录有可能和某个和saf的某个参数有关。我在一个安卓6.0的小米手机上禁用了文档提供器以后，传统模式就能正常读取文件目录了。当然这只是我的猜测，因为我更熟悉的Chrome之类的软件更多的是直接调用了媒体库，而不是单独使用了tree权限。
我只是把我能想到的一些个人情况测试一下提供出来给你们做一个debug的参考，并没有冒犯的意思。faq我回这贴之前就看了，并没有看到关于传统模式看不到文件目录的说明，所以我没在前面关于saf的串回复而是选择了这个同为MIUI系统在传统模式上出bug的串里反馈了一下。

**Comment by Notsfsssf** [comment]
> > > 同样调用saf的chrome就没有这个问题，我怀疑是不是默认参数不合适。回头我用老一点的MIUI版本试一下，saf的默认参数应该不会影响内存读写权限的使用啊
> > 
> > 
> > 如果你不会看[FAQ](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E9%80%89%E6%8B%A9%E5%82%A8%E5%AD%98%E7%9B%AE%E5%BD%95)的话，我帮你复制过来
> > 回到正题，我们推荐选择的路径是 Pictures/PixEz ，当然一般来说这个路径不会从一开始就存在，所以往往文件夹需要自己来创建。
> > 具体一点的操作方式如下：
> > 点击右上角的三个点，选择「显示内部存储空间 (Show internal storage)」（如果是「隐藏内部存储空间(Hide internal Storage)」则无需再点选
> > 打开左侧栏，找到你的手机内部存储空间（一般为手机图标 + 手机型号，可用空间 XX GB）
> > 找到 Pictures 目录，如果你还没有 PixEz 目录则从右上角的三个点中选择「新建文件夹」 进入刚建立的 PixEz 目录，点击下面的「选择」
> > 注意，保存路径不能包含 Download (下载)目录，所以最好选择 Pictures/PixEz 路径。
> 
> 不是，我是说传统模式，我是说传统模式在获得读写存储权限以后依然不能读取文件目录有可能和某个和saf的某个参数有关。我在一个安卓6.0的小米手机上禁用了文档提供器以后，传统模式就能正常读取文件目录了。当然这只是我的猜测，因为我更熟悉的Chrome之类的软件更多的是直接调用了媒体库，而不是单独使用了tree权限。
> 我只是把我能想到的一些个人情况测试一下提供出来给你们做一个debug的参考，并没有冒犯的意思。faq我回这贴之前就看了，并没有看到关于传统模式看不到文件目录的说明，所以我没在前面关于saf的串回复而是选择了这个同为MIUI系统在传统模式上出bug的串里反馈了一下。

能否提供一下你的根目录的路径

**Comment by porSilent** [comment]
> 能否提供一下你的根目录的路径

虚拟sd卡的吗？/storage/emulated/0/

**Comment by Bailin7** [comment]
大佬你说的我听不懂

**Comment by Notsfsssf** [comment]
> 大佬你说的我听不懂

你可以点右边那个unsubscribe取消邮件订阅

**Comment by Notsfsssf** [comment]
> > 能否提供一下你的根目录的路径
> 
> 虚拟sd卡的吗？/storage/emulated/0/

目录也对的上....没办法了
我是照着规范写的，没有带其他特殊参数

**Comment by porSilent** [comment]
> > > 能否提供一下你的根目录的路径
> > 
> > 
> > 虚拟sd卡的吗？/storage/emulated/0/
> 
> 目录也对的上....没办法了
> 我是照着规范写的，没有带其他特殊参数

那估计是辣鸡小米阉割了什么东西，看看之后版本吧，试了几个老MIUI版本，只有安卓6以下MIUI版本的传统模式没问题

**Comment by Notsfsssf** [comment]
> > > > 能否提供一下你的根目录的路径
> > > 
> > > 
> > > 虚拟sd卡的吗？/storage/emulated/0/
> > 
> > 
> > 目录也对的上....没办法了
> > 我是照着规范写的，没有带其他特殊参数
> 
> 那估计是辣鸡小米阉割了什么东西，看看之后版本吧，试了几个老MIUI版本，只有安卓6以下MIUI版本的传统模式没问题

0.2.3已发布，更新一下看看有没有问题
