### ISSUE TITLE
为什么搜索r18g图的pid会被ban

### ISSUE THREAD

**Issue by Adflyyy** [Notsfsssf/pixez-flutter#440]
如图![www](https://user-images.githubusercontent.com/116634087/197731734-5056c631-c017-48bb-85a2-b1ee593037ed.jpg)

**Comment by Reisen-U** [comment]
不是软件的问题，是你账户设置当中屏蔽了r18g。可以访问网页端的pixiv设置(https://www.pixiv.net/setting_user.php)来更改。
