### ISSUE TITLE
Downloading banner of user feature 

### ISSUE THREAD

**Issue by kyoyacchi** [Notsfsssf/pixez-flutter#443]
Hi. Can you add downloading banner feature like downloading avatar by clicking on it.

**Comment by Notsfsssf** [comment]
[0.9.9](https://github.com/Notsfsssf/pixez-flutter/tree/0.9.9) added

**Comment by kyoyacchi** [comment]
> [0.9.9](https://github.com/Notsfsssf/pixez-flutter/tree/0.9.9) added

Thanks
