### ISSUE TITLE
Request: Switch default like button

### ISSUE THREAD

**Issue by l2eused** [Notsfsssf/pixez-flutter#444]
Add option to switch button for default "public like" to "private like"

> I mean "if I want to add illust as private, I need to press like button and tap agian to turn off public button. I need to tap button to add them as private as default"

**Comment by Notsfsssf** [comment]
long press favor button to private like as default?

**Comment by kyoyacchi** [comment]
Yes, a setting like this would be good.
![Screenshot_20221118-004643](https://user-images.githubusercontent.com/63583961/202566878-74db1c50-f0a4-43ce-bdc7-766b41ac9b72.jpg)
