### ISSUE TITLE
在导出小说时，无法显示界面下方的“导出”与“设置”选项。

### ISSUE THREAD

**Issue by YJ2CS** [Notsfsssf/pixez-flutter#450]
如图所示，当作者把章节名起的过长时，会直接无法显示下方的“导出”与“设置”选项。
![EOW10@1Q OI4~5(YDX3{_GG](https://user-images.githubusercontent.com/45024266/201471213-30827c7a-971f-4d7d-ad4a-a2b39a1a5797.jpg)

**Comment by Notsfsssf** [comment]
给个id吧

**Comment by YJ2CS** [comment]
作者：MC王大锤

https://www.pixiv.net/users/67801368

作品：关于我在荒谬怪诞世界里积德行善这件事 第二章 被悍女霸凌的校花被意外拯救并无法自拔陷入暗恋同时肉体再次被轻熟御姐医生所垂涎！

https://www.pixiv.net/novel/show.php?id=18424431
