### ISSUE TITLE
进入大图时加载动画有时无法正确显示

### ISSUE THREAD

**Issue by Grey-Throat** [Notsfsssf/pixez-flutter#46]
情况: 在某些图片点入大图时, 无法正确加载动画, 表现为白屏

> 正常时的动画
![Screenshot_20201008-095503_Gallery](https://user-images.githubusercontent.com/32970972/95406244-88aaee00-094c-11eb-9a77-29c6b31d3146.png)
异常时
![20201008_095516](https://user-images.githubusercontent.com/32970972/95406280-99f3fa80-094c-11eb-838f-d36232262a6e.png)
发生异常时的[录屏](https://drive.google.com/file/d/1A0XrGhQGYd0n8b1ruyjK8-IQxHJnXmF3/view?usp=drivesdk)

设备: 三星Note10+与iPhone8皆出现此问题
版本: 可能为0.2.1至今(不准确, 不确定是最近才有的还是一直存在)
复现步骤: 访问某些图片的大图即会出现, 但不是所有的图片都有此现象, 复现比较随机. 且同一张图在关闭客户端后再打开也有可能会正常, 录屏中异常的图Illust ID为79422340.

**Comment by Notsfsssf** [comment]
这个灰屏是出现错误时才会出现的，但是我并不能复现这个问题....也许他在某些特定机型出现    
![Screenshot_2020-10-08-20-51-48-887_com.perol.pixe.jpg](https://i.loli.net/2020/10/08/iyzBZKJs2VkbRtm.jpg)

**Comment by Grey-Throat** [comment]
复现的确有点玄学, 这张图我关了App重新开有时会正常有时又炸
首页刷图的时候总体出现概率大概是1/30或更小
请问adb抓log然后发上来之类的操作会有帮助吗, 没开发过App只能问些傻问题 😅

**Comment by Notsfsssf** [comment]
0.2.3已发布，更新一下看看有没有问题

**Comment by Grey-Throat** [comment]
更换新动画后已经没有这种问题, 感谢!
