### ISSUE TITLE
加载不出来，iOS14.1

### ISSUE THREAD

**Issue by tangminghan** [Notsfsssf/pixez-flutter#47]
如图
![Uploading 108907DC-8FF8-4FCB-97BA-D3234BC0CDC5.jpeg…]()

**Comment by tangminghan** [comment]
![Uploading 1FF0125C-9C7C-4CB7-82FF-0E9F4AED4C50.jpeg…]()

**Comment by tangminghan** [comment]
DioError [DioErrorType.DEFAULT]:SocketException: OS Error: Connection reset by peer, errno=54, address=app-api.pixiv.net.cdn.cloudflare.net.,port=65382

它这么说的

**Comment by tangminghan** [comment]
求大佬帮忙

**Comment by Notsfsssf** [comment]
这是昨天上午才出现的问题，就算最快apple的审核也得明天才能通过我的修复更新，一切看apple审核的脸色
