### ISSUE TITLE
Can't load pictures that are of sensitivity level of 4

### ISSUE THREAD

**Issue by No7079** [Notsfsssf/pixez-flutter#472]
The pictures can be loaded in Pixiv site after logging in, but can't be loaded in PixEz app.

And there are no setting options in Pixiv site. 

The ```sl``` value of the picture is 4. e.g., 54097201

(search first result of ```sl":``` in the source code of pixiv artwork page)

App version: 0.9.11-app-release

![](https://img-blog.csdnimg.cn/e6d4c8bf59bf4358ad0381486486e3dd.jpeg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_20,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0LzEyMzQ1Njc4OQ==,size_12,color_000000,t_100#pic_center)

**Comment by Notsfsssf** [comment]
![Screenshot_20230107-134950_PixEz](https://user-images.githubusercontent.com/16934707/211340718-b1aa8be4-5cfe-45f4-9184-3d8b604787b0.png)
maybe u can check your pixiv settings or birthday settings?

**Comment by No7079** [comment]
> ![Screenshot_20230107-134950_PixEz](https://user-images.githubusercontent.com/16934707/211340718-b1aa8be4-5cfe-45f4-9184-3d8b604787b0.png) maybe u can check your pixiv settings or birthday settings?

Ah 

It works

Those two options still needs to be turned on for viewing these... even illustrator didn't mark them.

Thank you for your suggestion. @Notsfsssf
