### ISSUE TITLE
如何屏蔽新的ai标识？

### ISSUE THREAD

**Issue by Steve-cn** [Notsfsssf/pixez-flutter#478]
如题，长按标识只能复制没法屏蔽

**Comment by Asankilp** [comment]
这个标识其实只是个文本，因为不同于其他前面带#的标签（因为是插画的一个“信息”而不是标签，只是显示在那里，p站网页版的AI生成也是显示在那里），至于屏蔽，在做了在做了（

**Comment by Steve-cn** [comment]
> 这个标识其实只是个文本，因为不同于其他前面带#的标签（因为是插画的一个“信息”而不是标签，只是显示在那里，p站网页版的AI生成也是显示在那里），至于屏蔽，暂时没有（

期待以后会有对应功能来屏蔽，辛苦各位大佬了

**Comment by SnowDream39** [comment]
你可以上p站网页版，在设置里面的“AI生成作品”选择部分隐藏

**Comment by Steve-cn** [comment]
> 你可以上p站网页版，在设置里面的“AI生成作品”选择部分隐藏

OK了，感谢

**Comment by Steve-cn** [comment]
> 你可以上p站网页版，在设置里面的“AI生成作品”选择部分隐藏

那个屏蔽没法彻底屏蔽，其实我想的是和tag屏蔽一样，直接不显示作品

**Comment by Notsfsssf** [comment]
这个是没法从api数据层面屏蔽的，都是官方返回的
但是app是可以提供屏蔽带有AI生成标识的作品，只是只能做物理屏蔽，客户端不展示，比如30个作品里10张是AI，那么就会显示20张，和tag屏蔽原理一样，感觉也不太实用，可以在下版加上
