### ISSUE TITLE
refresh failed

### ISSUE THREAD

**Issue by DogFather** [Notsfsssf/pixez-flutter#48]
![62A94591-F395-4A61-9B6C-7AE809BAA6C1](https://user-images.githubusercontent.com/33054546/95428655-e7d42700-097b-11eb-8679-e739adbaa4f5.jpeg)

**Comment by Skimige** [comment]
If you're using iOS, please upgrade to 1.2.1. This version fixes the connection problem.
(dumplicate of #47 )
