### ISSUE TITLE
有关桌面小组件的疑问和建议

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#485]
桌面小组件切换图片的时间周期是多少？能否添加一个切换按钮？

还有就是小组件显示的图片会无视我自己设置的屏蔽规则，这个可不可以优化一下？

**Comment by Notsfsssf** [comment]
周期是Android规定的最短30分钟，切换按钮一直不知道怎么设计，因为加个按钮挡住图会显得有点突兀
小组件的数据确实是无视了屏蔽规则，下版本会在写入时加个filter

**Comment by EmptyDreams** [comment]
> 周期是Android规定的最短30分钟，切换按钮一直不知道怎么设计，因为加个按钮挡住图会显得有点突兀 小组件的数据确实是无视了屏蔽规则，下版本会在写入时加个filter

按钮的话可不可以这样子：

现在不是点一下直接跳转到软件吗，改成点一下打开菜单这样子。

不过我没做过 app 开发，不知道这样可行不可行。

**Comment by EmptyDreams** [comment]
新版本添加了 filter，但是似乎没有添加 AI 的 filter，在设置中开启 AI 生成不可见后，小组件中仍然会显示 AI 生成的内容。
