### ISSUE TITLE
小说内图片显示错误

### ISSUE THREAD

**Issue by SherkeyXD** [Notsfsssf/pixez-flutter#486]
具体表现为所有图片都相同

示例
https://www.pixiv.net/novel/show.php?id=18697968

**Comment by SherkeyXD** [comment]
是 #395 中提到的问题吗

**Comment by Notsfsssf** [comment]
是同一个问题，p站开始使用webview展示小说了，而移动端的api并没有里面的数据协议，很显然官方打算放弃移动端的旧接口，以后新增的协议也是直接渲染到网页上 
目前也没有掌握和p站官网小说浏览通信的协议，只能搁置
