### ISSUE TITLE
[Bug] 打开艺术家页面，页面的滑动无法停止

### ISSUE THREAD

**Issue by tglsf** [Notsfsssf/pixez-flutter#494]
版本：0.9.14
Andriod 12.1

1. 从外部应用程序中打开一个艺术家页面，或者打开一个作品页面，点击艺术家的头像，进入艺术家页面。
2. 手指快速滑动，松开，页面开始滚动
3. 当瀑布流还在滚动时，点击屏幕不能停止页面滚动。

当从应用程序中打开艺术家的页面时，程序工作正常。只有在通过链接打开艺术家的网页时才会出现问题。

**Comment by Notsfsssf** [comment]
并未成功复现，能看看录屏吗
