### ISSUE TITLE
部分 AI 作画无法被正确识别

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#497]
不知道 pixez 是使用什么方法给 AI 生成的插画打上 tag 的，但是部分 AI 生成的并没有显示 AI生成。

比如说 pid：105663074

**Comment by Notsfsssf** [comment]
是p站识别的，有的用户不老实投稿不勾选AI作品，又没被p站识别到就没有带这个标识
我想过黑名单用户举报机制，但是维护起来需要精力投入，还是不搞这些了

**Comment by EmptyDreams** [comment]
> 是p站识别的，有的用户不老实投稿不勾选AI作品，又没被p站识别到就没有带这个标识 我想过黑名单用户举报机制，但是维护起来需要精力投入，还是不搞这些了

原来是 P 站自己加的，我还以为是 pixez 带的，那只能希望 P 站能把 AI 识别做得更好或者有质量比较高的开源模型了。
