### ISSUE TITLE
非直连功能没有找到（还是没写这个功能？）

### ISSUE THREAD

**Issue by B1ackSand** [Notsfsssf/pixez-flutter#52]
如果能够像之前一样可以设置选择不使用直连方式使用就好了，我在app找了一圈也没找到哪里可以取消。（如果有写这个功能的话我先在这里表示歉意。）

因为有时候感觉直连比我用的梯子要慢，但是这也是我最喜欢的第三方pixiv app，比较干净整洁嘛。

顺便支持一下作者，毕竟也是用了很久这软件:)

**Comment by Skimige** [comment]
[”「不要绕过 SNI 嗅探」到底是绕过还是不绕过？“](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E4%B8%8D%E8%A6%81%E7%BB%95%E8%BF%87-sni-%E5%97%85%E6%8E%A2%E5%88%B0%E5%BA%95%E6%98%AF%E7%BB%95%E8%BF%87%E8%BF%98%E6%98%AF%E4%B8%8D%E7%BB%95%E8%BF%87)

位置：设置 - 偏好设置 - 不要绕过 SNI 嗅探

**Comment by B1ackSand** [comment]
> [”「不要绕过 SNI 嗅探」到底是绕过还是不绕过？“](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E4%B8%8D%E8%A6%81%E7%BB%95%E8%BF%87-sni-%E5%97%85%E6%8E%A2%E5%88%B0%E5%BA%95%E6%98%AF%E7%BB%95%E8%BF%87%E8%BF%98%E6%98%AF%E4%B8%8D%E7%BB%95%E8%BF%87)
> 
> 位置：设置 - 偏好设置 - 不要绕过 SNI 嗅探

谢谢你！
