### ISSUE TITLE
PixEZ无法启动

### ISSUE THREAD

**Issue by block13566** [Notsfsssf/pixez-flutter#520]
具体表现为转圈，未开启不跳过嗅探

**Comment by block13566** [comment]
![Uploading Screenshot_2023-05-01-20-38-23-316_com.perol.pixez.jpg…]()

**Comment by frg2089** [comment]
我反复确认了好几次...
![image](https://github.com/Notsfsssf/pixez-flutter/assets/42184238/1d288423-b3e1-422d-a712-d43fb95939a1)

你好像没有成功上传图片...
