### ISSUE TITLE
sni嗅探是指不使用内置代理吗

### ISSUE THREAD

**Issue by xushet** [Notsfsssf/pixez-flutter#53]
rt

**Comment by Skimige** [comment]
从来没有内置代理，只是使用了一些小技巧绕过墙（的 SNI 嗅探），从而可以直连。

[”「不要绕过 SNI 嗅探」到底是绕过还是不绕过？“](https://github.com/Notsfsssf/pixez-flutter/blob/master/.github/FAQ.md#%E4%B8%8D%E8%A6%81%E7%BB%95%E8%BF%87-sni-%E5%97%85%E6%8E%A2%E5%88%B0%E5%BA%95%E6%98%AF%E7%BB%95%E8%BF%87%E8%BF%98%E6%98%AF%E4%B8%8D%E7%BB%95%E8%BF%87)
