### ISSUE TITLE
自定义取色在退出应用后就会失效

### ISSUE THREAD

**Issue by bilibili2233a** [Notsfsssf/pixez-flutter#536]
已经设置好颜色，一退出应用，再重新打开就变成默认的蓝色
版本是最新的0.9.20
![Screenshot_20230524_123105_com.perol.pixez.jpg](https://github.com/Notsfsssf/pixez-flutter/assets/99982054/6cbad8db-6377-4792-a907-5834669bea46)

**Comment by bilibili2233a** [comment]
现在更新到最新版之后，取色还是会失效。

**Comment by bilibili2233a** [comment]
现在更新到0.9.22
手动取色还是一样的问题

![Screenshot_20230606_100315_com.huawei.android.launcher.jpg](https://github.com/Notsfsssf/pixez-flutter/assets/99982054/94427a48-c93a-43cd-940b-5c4678ce60f2)

**Comment by bilibili2233a** [comment]
我是一退出应用，再重进就会变成默认的蓝色。
这是已经重新清除数据和缓存之后的视频:
https://github.com/Notsfsssf/pixez-flutter/assets/99982054/f4f8eac7-27a9-47a0-85bf-fa9df9d4a67d

**Comment by bilibili2233a** [comment]
刚刚更新后，还是这样🙃

**Comment by Notsfsssf** [comment]
我无法定位到问题...即使我开了avd从android 5 debug到14，有办法协助测试一下吗，我晚上会发测试包到这里或者能加tg group之类的im实时反馈一下就好了

**Comment by bilibili2233a** [comment]
该怎么协助测试呢？

**Comment by bilibili2233a** [comment]
好的，我已经加入Telegram群组了

**Comment by bilibili2233a** [comment]
开发者很有有耐心❤️，经历了手机平板的两次进不去，应用后最后一次正常打开了，退出后取色也是正常
