### ISSUE TITLE
在使用虚拟按键的 Android 设备上访问 Novel 内容时内容会被遮挡。

### ISSUE THREAD

**Issue by GuyZH** [Notsfsssf/pixez-flutter#539]
如标题所述，在使用虚拟按键的 Android 设备上访问 Novel 内容时内容会被底部虚拟按键遮挡。这可能是因为在新的版本中底部的虚拟按键不再半透明导致的。
![image](https://github.com/Notsfsssf/pixez-flutter/assets/96634831/9f82c6d7-2d72-483c-b0e7-75988f238c3f)

**Comment by Notsfsssf** [comment]
如果滑动到底部内容也不能完全拉出来吗，首页的导航栏有没有正确沉浸？

**Comment by GuyZH** [comment]
> 如果滑动到底部内容也不能完全拉出来吗，首页的导航栏有没有正确沉浸？

0.9.20 版本的首页界面，底部虚拟按钮区域是类似半透明的效果。0.9.21 版本变成了纯白色。
划动到底部也无法将内容拉出。

**Comment by Notsfsssf** [comment]
已修复
