### ISSUE TITLE
请在登陆界面中加入使用token登陆的选项，并在切换用户界面中加入复制token的选项

### ISSUE THREAD

**Issue by ChinaIceF** [Notsfsssf/pixez-flutter#545]
使用PixEz的一大好处就是不需要长期使用网络代理工具就可以访问pixiv，然而当在新设备上安装本软件时，需要使用网络工具进行登陆。如果此时拥有一台以前使用过本软件的设备，就可以复制账号的token直接在新设备上使用，免去登陆的环节。这样更能发挥该项目的一大优势，即与网路代理工具高度脱离。本issue源于参考旧版本的“shaft”应用拥有的此类功能。感谢你们对本项目的辛勤奉献！

**Comment by YHSanSheng** [comment]
0.9.21已经实现了可以自己closed下
