### ISSUE TITLE
使用script自定义文件名模式下保存单图片作品时文件名为null

### ISSUE THREAD

**Issue by Flithor** [Notsfsssf/pixez-flutter#547]
使用原始的script脚本就会出现这个问题
保存多图片作品的行为正常

**Comment by Notsfsssf** [comment]
看一下script写了什么，这个是调用webview处理js的

**Comment by Flithor** [comment]
说了是“原始”的
![Screenshot_20230604_104112_com perol pixez](https://github.com/Notsfsssf/pixez-flutter/assets/23412916/a220a2a1-a204-4c7e-aa17-b78c2806a7f6)
不过似乎不是所有作品都会出现这个问题来着
这个作品可以正常保存名字  
https://www.pixiv.net/artworks/97268145
这个作品会保存成null  
https://www.pixiv.net/artworks/108612847

**Comment by Notsfsssf** [comment]
已修复

**Comment by Flithor** [comment]
顺手给字段加个注释呗

**Comment by Notsfsssf** [comment]
https://github.com/Notsfsssf/pixez-flutter/blob/13cde0a6f1106d9aac956b7e548bf03f69c7b712/lib/models/illust.dart#L54
