### ISSUE TITLE
APP作者主页是空白的，网页能看到主页内容

### ISSUE THREAD

**Issue by 1429886467** [Notsfsssf/pixez-flutter#565]
![Screenshot_2023-07-11-20-07-46-287_com perol pixez](https://github.com/Notsfsssf/pixez-flutter/assets/107488796/5cac866e-0a7f-4ccc-9b7e-7ed0bb11d8f8)
![Screenshot_2023-07-11-20-08-03-614_com android chrome](https://github.com/Notsfsssf/pixez-flutter/assets/107488796/c66faba3-f994-4502-8eb2-d97a3683c649)

**Comment by Notsfsssf** [comment]
但他投稿的都是漫画啊，你点一下漫画?

**Comment by 1429886467** [comment]
> 但他投稿的都是漫画啊，你点一下漫画?

漫畫也是空白的
![Uploading Screenshot_2023-07-11-22-50-03-467_com.perol.pixez.jpg…]()

**Comment by Content10** [comment]
好像是含有外部链接的作品简介在app上都看不到，网页上能看得到

**Comment by 1429886467** [comment]
> 好像是含有外部链接的作品简介在app上都看不到，网页上能看得到，我换了几个旧版本好像也有这个问题，应该不是版本的问题了，不知道是软件哪个服务出了问题把外部链接全屏蔽了

应该不是这个问题，其他带有外部链接的图都能看，而且我在网页版上看的这个作者没有外部链接

**Comment by Content10** [comment]
> > 好像是含有外部链接的作品简介在app上都看不到，网页上能看得到，我换了几个旧版本好像也有这个问题，应该不是版本的问题了，不知道是软件哪个服务出了问题把外部链接全屏蔽了
> 
> 应该不是这个问题，其他带有外部链接的图都能看，而且我在网页版上看的这个作者没有外部链接

这样看我和你说的好像不是同一个问题了我另开一个是issue反馈好了，我说的是简介看不到，你的我再仔细看了下好像是图看不到

**Comment by Notsfsssf** [comment]
> ![Screenshot_2023-07-11-20-07-46-287_com perol pixez](https://user-images.githubusercontent.com/107488796/252658811-5cac866e-0a7f-4ccc-9b7e-7ed0bb11d8f8.jpg) ![Screenshot_2023-07-11-20-08-03-614_com android chrome](https://user-images.githubusercontent.com/107488796/252658833-c66faba3-f994-4502-8eb2-d97a3683c649.jpg)

给个画师id呗

**Comment by Thousandsnowy** [comment]
问题解决了吗 我这边很多作者都有这样的情况
