### ISSUE TITLE
有外部链接的作品简介在app上都看不到，网页上能看得到

### ISSUE THREAD

**Issue by Content10** [Notsfsssf/pixez-flutter#567]
我换了几个旧版本现在也有这个问题，前几天用着新版本和旧版本应该都没这个问题的，应该不是版本的问题了，不知道是软件哪个服务出了问题把外部链接全屏蔽了

_Originally posted by @Content10 in https://github.com/Notsfsssf/pixez-flutter/issues/565#issuecomment-1636646292_

**Comment by Content10** [comment]
![Uploading Screenshot_2023-07-15-12-40-58-265-edit_com.perol.pixez.jpg…]()

**Comment by Content10** [comment]
![Screenshot_2023-07-15-12-40-46-953_com perol pixez](https://github.com/Notsfsssf/pixez-flutter/assets/19535044/c99cf7a8-35b6-4cb8-8349-28a14bf81e62)

**Comment by Content10** [comment]
![Uploading Screenshot_2023-07-15-12-40-40-995-edit_com.android.chrome.jpg…]()

**Comment by Content10** [comment]
![Uploading Screenshot_2023-07-15-12-46-21-289-edit_com.perol.pixez.jpg…]()

**Comment by Content10** [comment]
![Screenshot_2023-07-15-12-40-40-995-edit_com android chrome](https://github.com/Notsfsssf/pixez-flutter/assets/19535044/5956b96d-a0b6-4004-82f0-aef8e4a65aa6)

**Comment by Content10** [comment]
![Screenshot_2023-07-15-12-49-32-517-edit_com perol pixez](https://github.com/Notsfsssf/pixez-flutter/assets/19535044/99bd4a52-53d6-47d5-a488-9a67f7c063cf)

**Comment by Notsfsssf** [comment]
![c3ac1c9e09a71c2379f3537c3d489b74](https://github.com/Notsfsssf/pixez-flutter/assets/16934707/18c06a78-b15b-4a0d-9b8f-c7ad4358d1ba)

测试了一下，最新的官方客户端上也是看不到的，最近pixiv有被google play下架过，可能是为了过审隐藏了这种简介，或者是接口升级

**Comment by 1429886467** [comment]
请问现在这个问题解决了吗
