### ISSUE TITLE
ios加载小说会卡死

### ISSUE THREAD

**Issue by popymy** [Notsfsssf/pixez-flutter#589]
加载一些长篇的就极容易卡死 重新安装过没用

**Comment by popymy** [comment]
![image](https://github.com/Notsfsssf/pixez-flutter/assets/93435454/c24f375f-8c20-4dc3-81bc-05e24160fd37)

**Comment by Notsfsssf** [comment]
如果能提供测试id就好了

**Comment by Notsfsssf** [comment]
> > 如果能提供测试id就好了
> 
> 有ios的未签版本吗 现在这个版本看不了小说太难受了🥹

我是问如果你能给出这个加载不了的小说的id就更方便我调试了

**Comment by popymy** [comment]
是瑟瑟的小说 不太好意思 但是我试过很多次大概率都加载不出来。 有些加载出来但是只限于查看评论以上内容，后面的滑不下去。
