### ISSUE TITLE
有外部连接的作品看不到简介，网页版能看到

### ISSUE THREAD

**Issue by 1429886467** [Notsfsssf/pixez-flutter#592]
![IMG_20230803_090110](https://github.com/Notsfsssf/pixez-flutter/assets/107488796/b93d3e95-f9e1-4b0c-882f-cc5d306f5462)
![IMG_20230803_090120](https://github.com/Notsfsssf/pixez-flutter/assets/107488796/244e0079-ab57-4fd2-b5e9-0610d6a5a3e3)

**Comment by SnowDream39** [comment]
参见#570

**Comment by 1429886467** [comment]
> 参见#570

感谢，刚才去推特看了下，p站官方说了这个bug修复了，不过pixez还是看不到链接。。。
