### ISSUE TITLE
Series 页存在文章显示数量限制问题。

### ISSUE THREAD

**Issue by GuyZH** [Notsfsssf/pixez-flutter#624]
如标题所述，Series 只能显示 30 条 Novel，在此之后的 Novel 无法显示。

您可以参考如下屏幕截图:
![image](https://github.com/Notsfsssf/pixez-flutter/assets/96634831/b2e4bdfc-5fcd-421d-82a0-a64f35d7f6eb)
![image](https://github.com/Notsfsssf/pixez-flutter/assets/96634831/e01460e3-40d8-4377-8929-4db04b93c34f)

**Comment by Notsfsssf** [comment]
有id不

**Comment by GuyZH** [comment]
> 有id不

[https：//www.pixiv.net/novel/series/10962698]()

除此之外，任意超过 30 个 Novel 的 Series 也都存在此问题。

**Comment by Notsfsssf** [comment]
已经进行了处理，下一版会带上这个修复

**Comment by Notsfsssf** [comment]
已解决
