### ISSUE TITLE
Please make these strings translatable

### ISSUE THREAD

**Issue by kyoyacchi** [Notsfsssf/pixez-flutter#629]
Can you please make these strings translatable?

![Screenshot_20231119-234850_1_1](https://github.com/Notsfsssf/pixez-flutter/assets/63583961/d40827b0-880f-4493-b2ce-b7fb5e38e654)
![Screenshot_20231119-233910_1_1_1](https://github.com/Notsfsssf/pixez-flutter/assets/63583961/44d88286-77f4-4fa2-847a-8129d0713efe)
![Screenshot_20231119-235207](https://github.com/Notsfsssf/pixez-flutter/assets/63583961/090caf9d-5bfd-4106-a0b8-f7dad15b2b3e)

"Loading..."
"Succeeded!"
"Failed!"
"Last updated at"
"Reply"
"Reply to illust"

**Comment by kyoyacchi** [comment]
Sorry for not specifying but can you also add "Pull to refresh" and "Release ready", and "Refreshing..."

**Comment by Notsfsssf** [comment]
These are untranslated texts that come with the default refresh control `easy_refresh`， but it seems that they are not used anywhere. Where do these texts appear? 🧐

**Comment by kyoyacchi** [comment]
> These are untranslated texts that come with the default refresh control `easy_refresh`， but it seems that they are not used anywhere. Where do these texts appear? 🧐

![Screenshot_20231127-193622](https://github.com/Notsfsssf/pixez-flutter/assets/63583961/c292d513-7d68-4efa-b224-dc7f8eaeca6b)
![Screenshot_20231127-193633](https://github.com/Notsfsssf/pixez-flutter/assets/63583961/d7acf2d0-1474-43e5-8c78-2e67ced24258)

**Comment by Notsfsssf** [comment]
I have unified all the `RefreshHeaders` and `Footers`. Currently, the Header is using `MaterialHeader`, without any text. The Footer should have been translated
[DefaultHeaderFooter](https://github.com/Notsfsssf/pixez-flutter/blob/124c1f64baf3e0857e035dd2bda647f169b21dbd/lib/component/pixez_default_header.dart#L5)
