### ISSUE TITLE
想请教关于直连的问题

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [Notsfsssf/pixez-flutter#63]
请问这个app的直连功能核心功能是如何实现的，如果方便的话能指明一下代码位置吗？感谢

因为最近在做类似的功能所以想参考一下这个项目设计思路

会注明代码来源，本项目的地址和您的名字以及遵循开源协议

**Comment by Notsfsssf** [comment]
如果你会android开发的话，看我旧项目Pix-ezviewer，readme里有标注实现的地方，用kotlin编写的，核心类是Rubysslsocketfactory，看了就理解了

**Comment by PeanutMelonSeedBigAlmond** [comment]
感谢您的回复

根据您的描述，我已经看懂了java/kotlin的实现原理，我想请教的是，对于dart，如何实现这个功能

因为我发现这个项目貌似不是用`PlatformChannel`调用java/kotlin代码来请求网络的

谢谢

**Comment by Notsfsssf** [comment]
直连的原理便是不携带sni信息，dart原生的api就可以实现

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 直连的原理便是不携带sni信息，dart原生的api就可以实现

感谢您的回复

根据这个思路，已经使用dart、kotlin/java都测试成功

再次表示感谢
