### ISSUE TITLE
传统模式下，下载图片之后会app奔溃

### ISSUE THREAD

**Issue by zkvvabcd** [Notsfsssf/pixez-flutter#65]
传统模式下，下载图片之后会app奔溃，目录下也没有文件
但是软件还是显示已经完成
![Screenshot_20201019-171810](https://user-images.githubusercontent.com/52879734/96427187-d23ee700-1230-11eb-8bbe-8b934364bc86.jpg)
![Screenshot_20201019-172147](https://user-images.githubusercontent.com/52879734/96427262-e7b41100-1230-11eb-89b3-597943d17ef7.jpg)

**Comment by Notsfsssf** [comment]
尝试一下更新到最新版，然后更换保存目录

**Comment by zkvvabcd** [comment]
> 尝试一下更新到最新版本，然后更换保存目录

感谢回复目前是最新版目录只能切换到/storage/emulated/0/和/storage/emulated/0/picture 目录下新建文件夹也无反应
目前换回saf方式工作正常

**Comment by Notsfsssf** [comment]
0.2.3已发布，更新一下看看有没有问题
