### ISSUE TITLE
[功能请求]: 在插画预览列表新增AI标识

### ISSUE THREAD

**Issue by sakarie9** [Notsfsssf/pixez-flutter#663]
一个示例，在插画列表的左上角增加一个AI标识供用户提前判断是否为AI作品，并在设置内新增一个是否开启此功能的开关

![无标题](https://github.com/Notsfsssf/pixez-flutter/assets/20642596/14b6eda1-b9ac-4a0f-8754-a0a39c86ed41)

**Comment by NeKoOuO** [comment]
> 一个示例，在插画列表的左上角增加一个AI标识供用户提前判断是否为AI作品，并在设置内新增一个是否开启此功能的开关
> 
> ![无标题](https://github.com/Notsfsssf/pixez-flutter/assets/20642596/14b6eda1-b9ac-4a0f-8754-a0a39c86ed41)
> 

這個好

**Comment by sakarie9** [comment]
aa04a803d63adeea767dd053e4bb6d458cb6f67a
