### ISSUE TITLE
两个图床都无法加载图片

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#694]
最近i.pixiv.re和默认图床都无法加载图片了。

**Comment by moyingji** [comment]
cloudflare 524 了 应该是图床访问量太高崩了？用其他图床吧暂时

**Comment by EmptyDreams** [comment]
> cloudflare 524 了 应该是图床访问量太高崩了？用其他图床吧暂时

请问还有什么靠谱的图床吗？

**Comment by yikuaiqianai** [comment]
我这个还是可以的（默认图床），就是改了默认在重启一下软件的好了。

**Comment by MoYingJi** [comment]
> 我这个还是可以的（默认图床），就是改了默认在重启一下软件的好了。

我这里默认图床时好时坏（大概率也是访问量的问题？

**Comment by MoYingJi** [comment]
> > cloudflare 524 了 应该是图床访问量太高崩了？用其他图床吧暂时
> 
> 请问还有什么靠谱的图床吗？

我也没什么 网上这种图床一搜一大把 但 要么天天崩要么速度慢都没i.pixiv.re之前的好和安心

**Comment by lxfly2000** [comment]
用默认就可以
