### ISSUE TITLE
自定义下载目录（下载到SD卡）

### ISSUE THREAD

**Issue by Jimmisama** [Notsfsssf/pixez-flutter#702]
应该有两种实现方式。。。一种是请求权限手动选择sd卡，一种是接口（比如Chrome，b站客户端）我也不清楚

隔壁Shaft能自定义下载目录。。。现在还是有部分安卓设备能支持sd卡的。。。LSP文件量比较多。。求求适配呜呜呜

**Comment by frg2089** [comment]
SAF 模式应该能做到这个
更多 -> 偏好设置 -> 平台特殊设置 -> 保存路径 -> SAF
