### ISSUE TITLE
App 启动时会闪一下白色的配色。

### ISSUE THREAD

**Issue by EmptyDreams** [Notsfsssf/pixez-flutter#703]
无论主题色设置为什么颜色，在app启动的瞬间，都会闪一下白色的配色，然后再修改为设置的配色，这个在黑夜模式下很显眼，而且很晃眼睛，不知道能否进行改进？

**Comment by Notsfsssf** [comment]
启动app时，系统是否开了暗色模式？冷启动这一下是系统决定的没法改

**Comment by EmptyDreams** [comment]
> 启动app时，系统是否开了暗色模式？冷启动这一下是系统决定的没法改

系统决定的话那确实没法改。
