### ISSUE TITLE
”悄悄关注“已关注的用户会取消关注

### ISSUE THREAD

**Issue by nothingshiru** [Notsfsssf/pixez-flutter#731]
Pixez进入一个已关注用户的主页，在右上角菜单里点击”悄悄关注“，会直接取消关注该用户，需要再次点击菜单里的”悄悄关注“才能真的悄悄关注。

Pixiv官网的关注旁边的菜单里是这样的：
- 未关注用户，菜单里是”悄悄关注“
- 已公开关注用户，菜单里是”设为不公开“
- 已悄悄关注用户，菜单里是”设为公开“

Pixez能不能也这么做？根据不同的关注状态，显示不同的选项

**Comment by Loy-K** [comment]
啊，原来是这样，那我岂不是误删了一堆关注，有办法找回吗
