### ISSUE TITLE
Can't play ugoira

### ISSUE THREAD

**Issue by uaevuon** [Notsfsssf/pixez-flutter#736]
After touching the play button, it just stuck at the first frame.

 0.9.43 Vital
com.perol.play.pixez

Android 14

**Comment by Notsfsssf** [comment]
need arkwork link to debug

**Comment by uaevuon** [comment]
> need arkwork link to debug

Every ugoira arts have this issue. 
Tell me how to extract log and I can upload logs.

**Comment by Notsfsssf** [comment]
https://github.com/Notsfsssf/pixez-flutter/assets/16934707/a31d5c00-ad25-49e9-b3c6-b26599a4d9c4

**Comment by uaevuon** [comment]
https://github.com/Notsfsssf/pixez-flutter/assets/3542715/b7b4d202-1d2f-4d5b-b685-2a85208a6cfa

No loading bar at all.

**Comment by uaevuon** [comment]
Sorry. Found the reason.

Adguard's https filtering has issue with pixez. After excluding https filtering on pixez, it works.
