### ISSUE TITLE
请问会不会对鸿蒙next支持

### ISSUE THREAD

**Issue by shiyazi** [Notsfsssf/pixez-flutter#738]
软件很好用，不知道会不会适配next

**Comment by Notsfsssf** [comment]
我肯定是乐意适配的，我需要等到next正式推出后再适配，当然前提是next让三方应用安装的话

**Comment by RxinnotRstar** [comment]
> 我肯定是乐意适配的，我需要等到next正式推出后再适配，当然前提是next让三方应用安装的话

我问了一位正在开发鸿蒙next软件的开发者，希望对你有帮助
![a13bfc9759b39e958b97f67c495c0c10](https://github.com/Notsfsssf/pixez-flutter/assets/56676566/425337fe-aa87-4047-a17d-7b4a20dd436d)

**Comment by shiyazi** [comment]
好的，感谢大佬回答🙏希望到时候侧载能放开点，大佬这基本上是最好用的pixiv第三方版本了

**Comment by caiweihan** [comment]
太好了！我昨天 MatepadPro 13.2 收到了鸿蒙5.0的正式版推送，现在只有 PixEz 和 Bitwarden 需要用安卓版。请问作者有支持鸿蒙next的时间表吗？我已经通过 https://github.com/likuai2010/auto-installer 安装了 ClashMeta，说明侧载应用是可行的 @Notsfsssf
