### ISSUE TITLE
option to disable icon animation 

### ISSUE THREAD

**Issue by kyoyacchi** [Notsfsssf/pixez-flutter#746]
Can we have an option to disable that animated rounding icon thing at the app start? It appears everytime i open a fanart from a link and felt annoying, sorry if i am being offensive, could you consider please? (Çince bilmiyorum, İngilizceyle idare ediver)

**Comment by Notsfsssf** [comment]
如果网络能够正常连接到pixiv，可以去app内more->preferences->network->Disable SNI Bypassing, 打开开关，这样启动动画就没了

If your network can connect to pixiv normally, you can go to more->preferences->network->Disable SNI Bypassing in the app and turn on the switch so that the startup animation will disappear.
