### ISSUE TITLE
自己建了图床 限制了前端请求路径 但是pixez里只能保存域名 不能保存域名带/

### ISSUE THREAD

**Issue by weiyongzenqi** [Notsfsssf/pixez-flutter#791]
担心不认识的人恶意刷流量 想加入这个限制

**Comment by Notsfsssf** [comment]
就是Https://host.com/xx/xx 这样吗

**Comment by weiyongzenqi** [comment]
> 就是[Https://host.com/xx/xx](Https://host.com/xx/xx) 这样吗

感谢回复 是的

**Comment by Notsfsssf** [comment]
下个版本加入吧，这个版本已经发上去了

**Comment by Notsfsssf** [comment]
下个版本加入吧，这个版本已经发上去了

**Comment by weiyongzenqi** [comment]
> 就是[Https://host.com/xx/xx](Https://host.com/xx/xx) 这样吗



> 下个版本加入吧，这个版本已经发上去了

感谢!

**Comment by 1210718010** [comment]
> 就是[Https://host.com/xx/xx](Https://host.com/xx/xx) 这样吗

端口号也能麻烦加一下吗，我也是自己反代的，但是部署在家里，运营商把443端口封了，用的是其他端口号
[https://host.com:port](https://host.com:port)
