### ISSUE TITLE
flutter_inappwebview 6.1.0 with InAppWebView widget macOS and Windows support

### ISSUE THREAD

**Issue by pichillilorenzo** [Notsfsssf/pixez-flutter#799]
Hello @Notsfsssf, I'm the author of the [flutter_inappwebview](https://github.com/pichillilorenzo/flutter_inappwebview/) Flutter plugin and I found out that your project is using it!
I recently updated the plugin with InAppWebView widget macOS and Windows support!

I would really like to add your project to the [Showcase](https://inappwebview.dev/showcase) page of the official plugin website.
It shows an open list of apps built with Flutter InAppWebView (both open and closed source).

So, may I have your permission to add it there?
If yes, I would like to have just a simple description of what `flutter_inappwebview` plugin was used for, and for which feature in your app.
For the screenshots and app logo, maybe, I could use the ones you have in your repository or on the app stores.

Hope to receive a positive feedback, thanks a lot!

**Comment by Notsfsssf** [comment]
当然可以，我主要用flutter_inappwebview 来实现app的登录功能，并且利用`shouldOverrideUrlLoading` 来捕获web的重定向实现PCKE的登录功能

Of course!This app mainly uses flutter_inappwebview for logging in on the web, specifically utilizing `shouldOverrideUrlLoading` for handling the login redirection.

**Comment by pichillilorenzo** [comment]
App added! Thanks a lot!
