### ISSUE TITLE
点击首页的收藏按钮有延迟

### ISSUE THREAD

**Issue by xushet** [Notsfsssf/pixez-flutter#81]
点击收藏时要等1秒左右才会收藏成功的反馈动画，这是网络问题还是手机性能原因？

**Comment by xushet** [comment]
不仅是首页，貌似只要是瀑布流显示的图片收藏按钮都是有延迟

**Comment by xushet** [comment]
图片详情页的收藏按钮也有延迟

**Comment by Romani-Archman** [comment]
延迟是因为等待star请求.这确实是个问题,有可能会让人误以为没点中.
我觉得可以增加一个CircularProgressIndicator,虽然在瀑布流里会有点不太好看.

**Comment by kunaguero10** [comment]
我这边收藏的时候无法选择tag，华为7T
