### ISSUE TITLE
在之前#791已经实现的Issues中,新遇到了一个bug

### ISSUE THREAD

**Issue by weiyongzenqi** [Notsfsssf/pixez-flutter#821]
https://github.com/Notsfsssf/pixez-flutter/issues/791
感谢实现上个Issues 在上面的Issues中 可以正确使用自定义前端路径预览图片以及点开图片查看大图时下载
但是在首页未点开图片 长按某个图片下载时会失败,任务进度为0
可提供已经搭建好的图床测试

**Comment by Notsfsssf** [comment]
可以上tg发我一下图床我试试
