### ISSUE TITLE
手势操作问题

### ISSUE THREAD

**Issue by zxc173123** [Notsfsssf/pixez-flutter#838]
安卓14，澎湃1.0
划动返回上一页会直接卡死闪退并弹提示
![Screenshot_2024-11-23-23-16-39-010_com perol pixez](https://github.com/user-attachments/assets/fb500ede-ef84-442f-a0ad-9c650ad5fb8e)

**Comment by Notsfsssf** [comment]
不要使用测试版桌面，你用chrome也是一样会闪退的
