### ISSUE TITLE
[bug] 最新版出现网络连接错误和软件内部错误

### ISSUE THREAD

**Issue by PYUDNG** [Notsfsssf/pixez-flutter#845]
更新到最新版后出现的问题，更新前正常使用无问题。
### 错误一
如图，打开主页、排行和速览页面都展示出421错误：
![Screenshot_20241204_130648](https://github.com/user-attachments/assets/64bd693e-4e72-4349-93bc-53b70a21638b)
![Screenshot_20241204_131152](https://github.com/user-attachments/assets/9174e0a8-e15e-4519-9c01-9e4d6bd91709)
### 错误二
如图，通过历史记录点进图片/在搜索框输入id进去图片后，出现此错误
![Screenshot_20241204_130828](https://github.com/user-attachments/assets/6f306094-0980-4c22-83e3-4ba0dd0dec02)

**Comment by PYUDNG** [comment]
刚刚看了PixivShaft软件也出现了相同的报错，怀疑是pixiv改了client api？
421错误是开启了绕过SNI嗅探开关时的报错，如果关闭开关走代理，则报错代码为404。

**Comment by Justin3298** [comment]
SNI关闭后可以正常使用啊，把梯子开起来就行

**Comment by PYUDNG** [comment]
SNI关闭开梯子连不上，刚刚测试显示`connection terminated during handshake`（我梯子可以确定是没问题的，可以打开pixiv.net网页，并且开的是全局）

**Comment by asadahimeka** [comment]
感觉是p站的客户端API接入了CF导致的，之前i.pximg.net也是这个问题，导致的我的图片代理直接报废
但是我用postwoman测试还是能通的
![image](https://github.com/user-attachments/assets/1d44d822-40a9-4c9f-a962-97309d0104d6)

**Comment by xianren152** [comment]
> 刚刚看了PixivShaft软件也出现了相同的报错，怀疑是pixiv改了client api？
> 421错误是开启了绕过SNI嗅探开关时的报错，如果关闭开关走代理，则报错代码为404。

shaft现在没问题
