### ISSUE TITLE
请问能否加个选项让多页图进入后折叠

### ISSUE THREAD

**Issue by piaopiaomofa** [Notsfsssf/pixez-flutter#87]
现在多页图点进去是直接纵向显示全部，如果数量多的就需要多花时间下滑才能看到图片详细信息，能否加一个选项可选择多页图进入后是折叠成单页或者全部展开？谢谢

**Comment by Notsfsssf** [comment]
右上角有个直达的按钮吧，虽然有时候不好使，多按几次也会到（因为高度没有计算完）
