### ISSUE TITLE
Release in Play Store? 

### ISSUE THREAD

**Issue by AkazaRenn** [Notsfsssf/pixez-flutter#9]
It looks good, would be great if it can be auto updated through Play Store.

**Comment by Notsfsssf** [comment]
I once put this app on google play. Although I filled out the rating in the age rating report, google still removed my app on the grounds of'explicit pornography'.
I don’t know how google defines this standard, but I know very well that if my app is removed again, my google account will also be blocked.

**Comment by AkazaRenn** [comment]
@Notsfsssf That's weird, because there's another Pixiv viewer called PxView living finely. But anyways thanks for replying, I'll leave this issue for you to decide whether to close it or not. Thank you for your effort on it!

**Comment by Notsfsssf** [comment]
Now release in [play store](https://play.google.com/store/apps/details?id=com.perol.play.pixez)

**Comment by AkazaRenn** [comment]
@Notsfsssf thank you!
