### ISSUE TITLE
请问能否增加对pixiv.me的链接跳转支持

### ISSUE THREAD

**Issue by piaopiaomofa** [Notsfsssf/pixez-flutter#96]
在推特上有些作者的p站链接用的是pixiv.me，点开无法直接跳转app，希望能增加pixiv.me的链接跳转支持，谢谢

**Comment by Notsfsssf** [comment]
给一下示例链接吧...

**Comment by piaopiaomofa** [comment]
> 给一下示例链接吧...

https://twitter.com/96mimo414
pixiv.me/user_uuxx8345

**Comment by Notsfsssf** [comment]
> > 给一下示例链接吧...
> 
> https://twitter.com/96mimo414
> pixiv.me/user_uuxx8345

这种link是访问网页解析后跳转的，是不支持直连的，你可以在跳转之后，把https改为pixez就能跳转到应用内
