### ISSUE TITLE
请问能否支持上传自己的作品与删除自己的作品

### ISSUE THREAD

**Issue by Sansui233** [Notsfsssf/pixez-flutter#97]
如题。请问从绕过SNI的原理上这个功能有没有实现的可能性

**Comment by Notsfsssf** [comment]
是能够支持的，但是我不会加的，原因有几个:
-是存在画师可能会使用这个应用，但是投稿这么大的事情的话，还是官网搞定比较好，毕竟谁会随手就画一张上传呢 
-可能会存在用户滥用，乱传表情包,截图之类的（特指熊猫头)
-可能会存在用户把投稿当作网盘用，把p站没有的作品但是版权保护的来投稿，确实是存在这类用户
-可能会让官方疑惑突然出现很多质量比较粗糙的投稿
综上所属，如果您是一名大触，请用网页投稿吧:)

**Comment by Sansui233** [comment]
您说的很对，我都没考虑到这点😂当时是问画师朋友开不开P站账号，他说没梯子，我想到不管是维护梯子还是网页版直连用nginx对一般偶尔传个图的人而言都有点麻烦，给他安利了pixez，发现不能上传于是来问一下。不过确实如您所说，由于手机的过于便捷的特性还是不做投稿的功能为好。
