### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Irisitomi** [Notsfsssf/pixez-flutter#98]
输入用户名密码后点击登陆提示尝试登陆而后没有任何反应，软件为github上的最新版，尝试不同设备和网络环境，结果一样。
但点击没有账号可以正常建立账号并进入。

**Comment by KELVIIN-HUANG** [comment]
同样遇到了这个问题。。。开启代理也无法登陆

**Comment by Notsfsssf** [comment]
旧的登录接口不再允许弱密码登录了，需要前往官网修改为强密码即可

**Comment by Irisitomi** [comment]
试了一下，确实改为强密码就好了，谢谢大佬。
